### ISSUE TITLE
crashed after it finished doing first-time profiling .. i think

### ISSUE THREAD

**Issue by KristjanKr** [XCompWiz/Mystcraft-Issues#100]
http://paste.ee/p/ee67z - here is the log, and crash report is here: http://paste.ee/p/zCYLB.
hope the information helps :)

**Comment by XCompWiz** [comment]
I clearly have missed a null pointer.  I do that sometimes, especially when writing large bodies of code in one pass....
Thanks for the report! I'll have this fixed for the next release. :)

**Comment by XCompWiz** [comment]
Yup, dumb error on my part. Easy to do.
Fixed and the fix will be in the next release. :)
