### ISSUE TITLE
ChunkProfiler instances

### ISSUE THREAD

**Issue by sfPlayer1** [XCompWiz/Mystcraft-Issues#102]
While looking at a FC2 heap dump I've observed that there's 2 live (as in still referenced) ChunkProfiler instances in the heap.

I don't know how exactly it works, but there being more than one may suggest a bug and keeping them around after the profiling finished may be another one. I'd expect it to get rid of anything but the results after finishing.

**Comment by XCompWiz** [comment]
Not a bug. Perhaps not a great name for the class that stores the data, though.

Every age has a ChunkProfiler class attached which stores the data associated with the block profiling for that age. It's like keeping the age data loaded.

Profiling for ages never finishes. The baseline profiling finishes once it is happy, but ages continue profiling to get a better image of that age.  Ages profile as they generate.

Thanks for keeping an eye out though! I always appreciate it. :)
