### ISSUE TITLE
Straight to profiling

### ISSUE THREAD

**Issue by tacogerbil** [XCompWiz/Mystcraft-Issues#103]
Whenever my kids or myself launch our modpack (technic Launcher), upon loading it will go straight to Mystcraft profiling.  After several minutes the images/text on the screen appear showing you are currently profiling and a button in the center giving you the option to exit the profiling.  Exiting normally ends up crashing the launcher.  Big issue here is that we only play SMP on my server... Kids get very confused as to what's going on.  Is there a way to stop this and make it so that the profiling will not occur unless you click on the single player game?  
Thank you for such an amazing mod; my 2 boys love it ;)

**Comment by mSt3in** [comment]
The profiling is a necessary evil.   It was decided unwise to allow players to play SMP while profiling is happening.  

The solution is to wait it out.  It's only done once, when the world is first created. (Some mods, specifically BoP, can make it take a REALLY long time.)

**Comment by tacogerbil** [comment]
I mean the clients.  The clients are only being used to play SMP.. My boys and nephews.  I may be misunderstanding the process....  I was under the assumption that the server did the profiling for the worlds and clients did not (at least while playing on a dedicated server).. This is happening before you ever get a chance to join a multiplayer game.. literally at the completion of the client/modpack loading.. at the point where it would normally go to the main menu and allow the player to either select single player or multiplayer it instead immediately goes straight to profiling..

**Comment by Otto42** [comment]
Can confirm that this happens if you update to Mystcraft 0.11.13 in the Direwolf20 1.4.1 modpack. On startup, the game goes directly into a Single Player world and begins the profiling process. The menu is only displayed for a second or two before this happens.

Downgrading to Mystcraft 0.11.11 solves the issue.

This might be related to https://github.com/XCompWiz/Mystcraft-Issues/issues/98.

**Comment by XCompWiz** [comment]
Actually, you were supposed to be able to connect to a server even with the baselining running. Should be possible. Without crash logs I can't help you further.
There are configs now, to allow preferred method of baselining. :)
