### ISSUE TITLE
Null pointer exception during initial profiling.

### ISSUE THREAD

**Issue by levicc00123** [XCompWiz/Mystcraft-Issues#107]
full crash log can be found at https://gist.github.com/levicc00123/a10bfca033067102605d

**Comment by Tsunayoshi** [comment]
Same here. Games crashes during first profiling and can't be started anymore

**Comment by heldplayer** [comment]
Try using the fix for bspkrCore as described in the changelog. (Disable the mobs on the main menu)

**Comment by Tsunayoshi** [comment]
Yeah, that helps. It's not crashing anymore, only freezing completely and running cpu at full 100%. But thats not the issue here. This problem is solved for me.

bspkrsCore.cfg:
    # Set to true to show your logged-in player and a random mob on the main menu, false to disable. [default: true]
    B:showMainMenuMobs=false
