### ISSUE TITLE
"Baseline Profiling world unloaded before time!" logged incorrectly

### ISSUE THREAD

**Issue by nallar** [XCompWiz/Mystcraft-Issues#109]
When any world unloads (not necessarily the profiling world), "Baseline Profiling world unloaded before time!" is logged.

`InstabilityDataCalculator.onWorldUnload` checks `running` before checking whether `dimId` matches with the world's dimension ID.

**Comment by XCompWiz** [comment]
I'll double check this, but "before" isn't relevant given the way you phrased it. It should check both, and then order doesn't matter.

**Comment by XCompWiz** [comment]
OK, checked the code and the issue is that it NEVER checks the dim id... *facepalm* Oops. I'll fix this when I next code.

**Comment by XCompWiz** [comment]
Fixed for next release.

**Comment by Tomson124** [comment]
I think you can close the issue @XCompWiz 
Bug is fixed for me :)

**Comment by XCompWiz** [comment]
Thanks! :)
