### ISSUE TITLE
Client Crash: "Cannot Hotload Dim: Overworld is not Loaded!"

### ISSUE THREAD

**Issue by Xiaminou** [XCompWiz/Mystcraft-Issues#110]
Forge: 1448
Mystcraft: 0.11.13.00
Crash Report: http://pastebin.com/hJcB224F

My Client crashed upon teleporting to a mystcraft dimension. Overworld might not have been loaded, as it says, as in ExU's The Last Millenium.
Intended? Bug? Should I make sure my Overworld is loaded before joining any Mystcraft dimension?
Edit: I tried to load the overworld first and still crashed

Edit: While we're talking, I have to give feedback on Mystcraft's pre-world generation initialization thingy, I know you're forced to let it run if you want to play SSP, but I'd still like to be able to control if I want it to run or not. Since I don't do alot of SSP I haven't let it run yet and every time I launch minecraft it instantly overtakes before I can do anything and that's another 5 minutes of not being able to do anything before I can stop it. Please give more control. (if I missed a config option or something ignore this)

**Comment by Cealian** [comment]
Have the same problem

i was in The Last Millenium from Extra Utilities when it happened for me

Forge: 10.13.4.1448
Mystcraft: 0.11.13.00
Crash Report: http://pastebin.com/LdejyjL5

**Comment by spocane** [comment]
I too am getting this error.

I only get it when switching from SSP to SMP

http://pastebin.com/a3DwzfZ2.

**Comment by XCompWiz** [comment]
Might be a conflict with the per-instance baselining. Try on latest Mystcraft.

**Comment by spocane** [comment]
still the same crash with most recent. : mystcraft-1.7.10-0.12.1.00.jar

**Comment by XCompWiz** [comment]
Could you provide a log/crash report, @spocane?
