### ISSUE TITLE
[request] configoption to disable profiling on title screen

### ISSUE THREAD

**Issue by Tsunayoshi** [XCompWiz/Mystcraft-Issues#111]
Hi,

i'am profiling for an hour now (i7 3770 @3,4GHz) 32GB Ram (6 for MC). The progressbar is only at 1/4 and the games freezes completly now. cpu is still at 100%...
Could you please add an option to disable the profiling at title screen. My friends and I only play online on a private server with this pack. Is this really necessary for server play??
The singleplayer button is removed in this pack, so it is not possible to start a single player world.

**Comment by Tsunayoshi** [comment]
I have done profiling after a couple of trys.
Disabling the texturpack helps a lot! Maybe you can disable the texturpack for the first profiling to be sure it's quick.
Profiling was done in about 25min. I will now try uploading the profile in my pack, so the other players are ready to play smp directly.

A option to disable it would be nice anyway. But if you need the profiling for smp too, this can be closed.

**Comment by Bogdan-G** [comment]
"profiling on title screen", please in file `[minedir]/config/splash.properties` change `enabled=true` in `enabled=false` and test run.

**Comment by Tsunayoshi** [comment]
It doesn't work. But the uploaded profile in the modpack works for me.

**Comment by XCompWiz** [comment]
If you are set to do per instance baselining then you don't actually have to wait for it to finish before you can connect to a server.
There are configs now.
