### ISSUE TITLE
Trade dialog with Mystcraft villager doesn't display properly

### ISSUE THREAD

**Issue by andrewmellinger** [XCompWiz/Mystcraft-Issues#113]
Even with no other mods (except forge) the dialog won't display more than two little boxes.  I've tried it with forge 1291 and 1448 and neither work.  There is nothing interesting in the logs, and otherwise the games appears to work fine.

I am using Java 1.7.0_75, give it 6GB of ram, and no other changes.

I've attached a screen shot with the problem dialog.

Any ideas about how I can collect more data?

Thanks.

![screen shot 2015-06-30 at 6 41 38 pm](https://cloud.githubusercontent.com/assets/5805856/8443915/f0403a54-1f58-11e5-9a2a-d4312536cde6.png)

**Comment by Bogdan-G** [comment]
enable debug mode forge and mods.

1)  reset the config mods
2) test forge 1380/1408/1420
3) Attach the logs to debug mode

**Comment by andrewmellinger** [comment]
Will do.  I'll run through all three versions.

**Comment by heldplayer** [comment]
I don't think the villager trading GUI is fully implemented yet.

If I remember correctly, you put emeralds in the top slot and you'll get something out in the bottom slot after a certain amount of emeralds.

**Comment by andrewmellinger** [comment]
Held player appears to be right.  It does function as an interface.  Put emeralds in the bottom slot and "sealed notebooks" appear in the top.  Sorry, I didn't recognize this from any of the videos or other screenshots I had seen.  So not easy to understand, but functional.

**Comment by XCompWiz** [comment]
Ya, it's not done yet, sorry. Got derailed. :P
