### ISSUE TITLE
Server Crash on using linking book

### ISSUE THREAD

**Issue by plazia** [XCompWiz/Mystcraft-Issues#115]
Was playing Mystcraft for the first time on my RR3 pack (lots of mods) and created a linking book. Put it down and tried to go back to the place. Server crashed.

Crashlog is here.

http://pastebin.com/vXzcZB8X

**Comment by XCompWiz** [comment]
Looks like your linking book is bugged and doesn't have a dimension id.
I've fixed the crash bug here for the next build, but I expect that the book won't work otherwise.
