### ISSUE TITLE
Automatically update contents of D-books from 0.10.13 on load

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#116]
This affects D-books, not L-books, in bookstands and lecterns, that were originally placed in a 164 world.

Repeat-by: Play in 164, 0.10.13., put D-books into the bookstand or lectern. Visit them.

Valid age, all happy.

Update to 1710, mystcraft 0.12.0.

Open the link book. You see the front and back cover, no pages, and 0/0 for the count.

Remove the book, close the GUI, open it back up, and place the book back in: Works just fine.

**Comment by XCompWiz** [comment]
Yes, you need to pick it up before it will work, but I've talked about this before.
I could try adding an update check on TE load, though.

**Comment by keybounce** [comment]
Then I've missed that this was an issue previously discussed.

Alright, known issue and work-around it is.

**Comment by XCompWiz** [comment]
This no longer applies to anything, since books that old no longer work anyway.
