### ISSUE TITLE
Crash with AE2 Compass

### ISSUE THREAD

**Issue by king05** [XCompWiz/Mystcraft-Issues#118]
Hi,
I got this crash on one map from my server:
http://pastebin.com/yVYeay0s
http://openeye.openmods.info/crashes/1923f148c318e7594cb3a7daca1a6c1c
I first thought it has only somethig to do with AE2 like openeye crash report said on the webpage.....
But after i rebuild this pack and test it with the crash world, i got the crash when i add mystcraft to the mods again...
Here is the Issue on the Applied energistics github:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1708

Sorry if I have some mistakes in my english.... I come from germany..
Sincerly
King05

**Comment by XCompWiz** [comment]
Without looking at the AE2 code for that function I can't say it looks like Mystcraft is involved. At most something is missing from a Mystcraft dimension that AE assumes will be there.
So basically, unless one of text AE2 devs comes to me with info on how Mystcraft missed something they expected, I'm going to class this as an AE issue.
