### ISSUE TITLE
Crash with TARDIS MOD and Looking Glass

### ISSUE THREAD

**Issue by DinixM** [XCompWiz/Mystcraft-Issues#121]
I recently got a crash with a Linking book used in the presence of ShaneDarkholme's TARDIS Mod. Not sure if it's Looking Glass or the TARDIS Landing pad at fault here, but I thought I should post the crash log to you and him, just in case. 
http://pastebin.com/MrVF7kcc
Using Pastebin to not flood the text box. To reproduce my crash, one would link a Linking Book near to the Landing Pad block and/or the TARDIS itself, then open the book. 
Thanks for your time.

**Comment by XCompWiz** [comment]
Little bit of both, I expect.
The Tardis mod should insulate itself a bit here, and check for that null pointer.
LookingGlass needs to improve how it handles updating the TE information.

And you should have created this issue in the LookingGlass repo, not the Mystcraft one. ;)

**Comment by DinixM** [comment]
Sorry about that, little new to the whole bug-reporting thing. I honestly just found the first place to bug-report straight to you and went with it. I do better next time. Thanks for a quick response.

**Comment by XCompWiz** [comment]
No worries! :) I was trying to be silly in teasing you, while still educating. Sorry if I came across to harshly.

Thanks for the report, regardless. :)

**Comment by DinixM** [comment]
I kinda got the teasing bit, and I did get a chuckle out of it as well. I just wanted to be as transparent and helpful as I could. :)

**Comment by XCompWiz** [comment]
This issue was moved to XCompWiz/LookingGlass#14
