### ISSUE TITLE
Client Crash on Server with Infinity 1.9.0, after using a linkbook

### ISSUE THREAD

**Issue by KendziGE** [XCompWiz/Mystcraft-Issues#122]
Hey, I hope I'm right here.
I have updated my server from Infinity 1.7.0 to 1.9.0 (i know it's not recommended), after that I put a few extra mods with in. (Storage Drawers, EE3 and Iguana Tinker Tweaks).

I visited a friends base with the RFTools porter, no problems, then I used a Linking book back to the overworld and the game crashed and since then i crashed everytime I try to connect to the server.

Crashreport after using the Linkingbook http://pastebin.com/f2MsUX52
Crashreport after try to connect to the server http://pastebin.com/YdXFyC4V

I hope you can help ^^ thanks.

**Comment by KendziGE** [comment]
After the 5th reinstall of the modpack,everything works fine.

**Comment by XCompWiz** [comment]
I don't see anything useful in the crash logs, I'm afraid.  Since it works I'll close this until someone manages to replicate it.
Thanks :)
