### ISSUE TITLE
issue right clicking mystcraft villager

### ISSUE THREAD

**Issue by ratbag359** [XCompWiz/Mystcraft-Issues#124]
[Mystcraft]: Gui handler 8 did not return a gui screen instance
happens when right clicking villager from mystcraft.
Forge 1.7.10.448
mystcraft-1.7.10-0.12.2.00

**Comment by Terpo** [comment]
I can confirm this problem but it only happens on our server. Singleplayer is working fine.

forge 1.7.10 1566
mystcraft-1.7.10-0.12.3.01
current modlist: http://blog.terpo.org/upload/mc/modlist.txt

You can click on a villager in multiplayer but the gui is not opening. The log only shows up:
[19:16:54] [Client thread/WARN] [Mystcraft]: Gui handler 8 did not return a gui screen instance
[19:16:58] [Client thread/WARN] [Mystcraft]: Gui handler 8 did not return a gui screen instance

Also, after clicking on a villager the inventory is freaking out: 
http://blog.terpo.org/upload/mc/2016-04-17_19.39.03.png

I did take a look in the server log files but there is nothing serious about a mystcraft warning or error.

**Comment by PsYcho-83** [comment]
I have this problem too.
I have a FTB Infinity Evolved 2.5 Server running and on client side the 2.5 version too. Singleplayer is working but not in Multiplayer. I'm getting the same errors as @Terpo  ....

I also tried with the mystcraft-1.7.10-0.12.3.02 version but still get the same error

**Comment by Terpo** [comment]
We have created some random ages for libraries and now we have most of the pages found. Still a bug, but not a huge problem.

**Comment by PsYcho-83** [comment]
but you can't get the "dense ore" page without villagers if I understood right the documentation...

**Comment by XCompWiz** [comment]
Related to #156.

**Comment by XCompWiz** [comment]
Pretty sure .03 should have fixed this. :)
