### ISSUE TITLE
Crashing After a Few Seconds After Loading World

### ISSUE THREAD

**Issue by RoloEdits** [XCompWiz/Mystcraft-Issues#125]
http://pastebin.com/ivgn5j7z

I'm getting this crash in a super-flat testing world with the overworld preset

**Comment by RoloEdits** [comment]
also just happen in my normal world

**Comment by XCompWiz** [comment]
Do you have an mods which modify the spawning of animals? Looks like something produced an invalid spawn list.

**Comment by RoloEdits** [comment]
I'm afraid i don't understand,something like an alternative way of spawning animals like an auto-spawner? or like the cocoon from botania's garden of glass? Or something like Ender Zoo or Ore Spawn that adds new mods to the game.

**Comment by RoloEdits** [comment]
i think i found the source, i think its Godzilla mod having problems with spawning in the mobs after setting the mob not to spawn in the config.

thank you for your time

**Comment by Bogdan-G** [comment]
@RoloEdits Of course, you also removed the entity of spawn. But you haven't solved the problem as soon as someone else make a similar, problem will again and again repeat.

**Comment by XCompWiz** [comment]
Actually, he probably has found the cause of the problem.
The root of the problem (the bad code) is in vanilla. Modders should be careful when handling animal spawning is all.

Glad you found what was causing it. :)

**Comment by RoloEdits** [comment]
Thanks :)
