### ISSUE TITLE
ChunkProfiler instances amplify world leak issues

### ISSUE THREAD

**Issue by sfPlayer1** [XCompWiz/Mystcraft-Issues#127]
The world instances I'm currently observing as leaked by other mods retain most of their footprint (~90%) in the Mystcraft ChunkProfiler instance attached to them. It'd be nice to help mitigate the leaks by purging the profiler instance from WorldEvent.Unload, assuming that event fires properly.

**Comment by XCompWiz** [comment]
Noted. I don't think they actually retain any external references, but they probably don't get unloaded due to the way that MC handles loaded data.

**Comment by sfPlayer1** [comment]
I have no idea, I'd close the issue and wait for the problem to resurface.

**Comment by XCompWiz** [comment]
Cheers :)
