### ISSUE TITLE
Mekanism Digital Miner stops mining and cannot find blocks on returning even with Chunk loader

### ISSUE THREAD

**Issue by adamcogx** [XCompWiz/Mystcraft-Issues#130]
I have a Mekanism digital miner (and a chunk loader) mining in a mystcraft world and if I leave the world, the miner stops running (it's feeding a tessarect) and when I return, the miner says there are 0 blocks available to mine, but if I pull it up and re-place it, it finds all kinds of blocks to mine.  I contacted Mekanism devs and they said the issue is that Mystcraft unloads the dimension and overrides the chunk loader.

**Comment by XCompWiz** [comment]
What? Mystcraft certainly does nothing of the kind.  Mystcraft dimensions can unload, but they very much follow the rules of chunk loading.

I have seen instance of other mods taking it upon themselves to force other dimensions to unload, though. I'd suggest trying to find the minimum set of mods required to replicate this. :)

**Comment by adamcogx** [comment]
Thanks for the reply.  That's what I thought, I'm guessing it's most like
the Tardis mod.  I have an OutOfMemoryException as you can see below that
involves Mystcraft and Tardis:

java.lang.OutOfMemoryError: Java heap space
at net.minecraft.nbt.NBTTagIntArray.func_152446_a(NBTTagIntArray.java:35)
at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
at
net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
at
net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
at
net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:34)
at net.minecraft.world.storage.MapStorage.func_75742_a(SourceFile:45)
at
com.xcompwiz.mystcraft.world.AgeController.getChunkProfiler(AgeController.java:506)
at
com.xcompwiz.mystcraft.world.AgeController.registerDebugInfo(AgeController.java:251)
at
com.xcompwiz.mystcraft.core.MystcraftEventHandler.handleWorldLoadEvent(MystcraftEventHandler.java:106)
at
cpw.mods.fml.common.eventhandler.ASMEventHandler_300_MystcraftEventHandler_handleWorldLoadEvent_Load.invoke(.dynamic)
at
cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at
net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:247)
at
net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:705)
at
io.darkcraft.darkcore.mod.helpers.WorldHelper.getWorldServer(WorldHelper.java:35)
at
io.darkcraft.darkcore.mod.helpers.WorldHelper.getWorld(WorldHelper.java:27)
at
io.darkcraft.darkcore.mod.helpers.WorldHelper.getDimensionName(WorldHelper.java:61)
at
tardis.common.tileents.CoreTileEntity.writeTransmittableOnly(CoreTileEntity.java:1658)
at
io.darkcraft.darkcore.mod.abstracts.AbstractTileEntity.func_145844_m(AbstractTileEntity.java:73)
at
net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
at
net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:576)
at
net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)
at
net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
at
net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at
net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)

On Thu, Sep 10, 2015 at 12:53 PM, XCompWiz <notifications@github.com> wrote:

> What? Mystcraft certainly does nothing of the kind. Mystcraft dimensions
> can unload, but they very much follow the rules of chunk loading.
>
> I have seen instance of other mods taking it upon themselves to force
> other dimensions to unload, though. I'd suggest trying to find the minimum
> set of mods required to replicate this. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XCompWiz/Mystcraft-Issues/issues/130#issuecomment-139288805>
> .
>



-- 
Adam Greene, Lead Software Architect
adam@cognitivex.com / @aspnetaddict <http://twitter.com/#!/aspnetaddict> /
Linkedin  <https://ca.linkedin.com/in/kadamgreene>/  www.cognitivex.com
<http://www.cognitivex.com/> / 506.802.8648

*Please consider the impact on the environment before printing this email*

*NOTICE: This email and any files transmitted with it are confidential and
intended solely for the use of the individual or entity to whom they are
addressed. If you have received this email in error please notify the
system manager. This message contains confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system. If you are not the
intended recipient you are notified that disclosing, copying, distributing
or taking any action in reliance on the contents of this information is
strictly prohibited.*

**Comment by XCompWiz** [comment]
That's likely a separate issue until shown to be otherwise. I'm happy to help, but please create another issue report for it. :)
