### ISSUE TITLE
Odd, random crash related to worldgen. I think it may have to do with mystcraft

### ISSUE THREAD

**Issue by starg09** [XCompWiz/Mystcraft-Issues#132]
Well, here's how it happened: I mention other mods, although in the end the solution was to remove Mystcraft. That's why I'm reporting it here.

--------------------------

I was testing my pack's new version, where I added mystcraft (In FTB Launcher, code "frutas". I'm talking about v2.0.2). So, I decided to play for a bit and check no major problems happened after the update. I started a new world, played for around 1 hour without problems, then closed in a plain and went to sleep.

Today, I reopen the world, explore a bit more, and closed before going to have lunch. I want to note that before saving, I found a vanilla dungeon, broke the spawner, then went to the surface and closed. Also, I was relatively close to a Roguelike Dungeon (filled with spawners).

After getting back, I tried adding optifine, as I'd forgotten I wanted to check if there were any problems using it. Once I loaded the world, and moved 5 blocks in one direction, [this crash happened](http://paste.ee/p/6SOiE). I removed it after that, but [the same thing happened again](http://paste.ee/p/eccIx).

Then I noticed this in the crash report, regarding BetterFPS:

    Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@26b0c789) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@1ffc0737) returned non-null result: 0

So, I tried removing BetterFPS. [Nope](http://paste.ee/p/KKJDZ). Then, I tried removing the most recently updated mods one by one. Latest one was mystcraft, so I removed it. No more crash, the world continued working properly. Re-enabled BetterFPS, still no crashes.

I'm not exactly sure what caused it, but from the crash report it looks to me like it has something to do with spawners (maybe the ones from Roguelike? They're a bit different than the usuals.). Anyway, that's basically it. I hope this helps you enough. I guess I could upload a backup of the world before the removal of mystcraft, I think Arome does one as I load the map.

**Comment by Zsashas** [comment]
The first three lines of the actual report:

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98279_f(SourceFile:45)
	at hats.common.core.EventHandler.onEntitySpawn(EventHandler.java:83)

Maybe try without Hats?

**Comment by starg09** [comment]
I'll try that. I'm looking for the right backup to use, and will try loading without hats. Then I'll update.

**Comment by starg09** [comment]
Well, it looks like removing Hats (And HatStand) also doesn't cause the crash. Will try a couple of times with Mystcraft but without hats, see if it eventually crashes. If it does, then it was hats, but for some reason after I removed Hats it didn't mess up anymore. If it doesn't, then there might be some incompatibility between hats and mystcraft...

**Comment by starg09** [comment]
Tried several times (more than 10 each) loading the same world, with the following results:

* **Mystcraft + Hats:** Game crashes after 10-15 seconds, same crashes as the ones sent above.
* **Only Mystcraft:** Nothing. Game plays as usual, no crashes of any kind
* **Only Hats:** Same as above. No crashes, no problems.

So, I guess we're still on the same spot. I tried some other stuff, like going to peaceful, then back to hard to wipe all mobs present, but still it didn't crash.

**Comment by Zsashas** [comment]
It looks like it's from mobs spawning with hats from a Recurrent Complex spawner, possibly in an age.

**Comment by XCompWiz** [comment]
The error is very much in the hats mod not getting along with someone's mobs/spawners.  Mystcraft is probably just enabling the issue to be visible in this case, such as the mob/spawner is loaded in an age.

I'd check if removing Recurrent Complex also fixed the issue. If so, then it's probably Hats conflicting with that.

**Comment by starg09** [comment]
Hmm, I'll check about that then. Although, does mystcraft load any age in a world before any book is made? This is a world played for around 2 hours tops, with no stable base, and no mystcraft books made so far.

**Comment by starg09** [comment]
Well, it looks like it didn't crash this time. I'll contact the developer of Recurrent Complex then. Thanks for the help!

**Comment by XCompWiz** [comment]
You should probably report it to iChun.

**Comment by starg09** [comment]
He seems to have dropped support for 1.7 versions :/

2015-09-22 12:05 GMT-03:00 XCompWiz <notifications@github.com>:
