### ISSUE TITLE
Weather Shenanigans

### ISSUE THREAD

**Issue by Zsashas** [XCompWiz/Mystcraft-Issues#133]
Ages seem very likely (i.e: almost always) to have constant rain, which seems a bit...imperfect.

1: NEI weather toggle does nothing.
2: Zelda Sword Skills, the Song of Storms acts as if it's still on cooldown as long as I'm in an age that's raining. Normally the cooldown is simply you can't activate it for a minute after using it, and has nothing to do with the current weather.
3: Rain isn't always visible. Tombenpotter's Icarus wings don't allow jumping in rain while they are equipped, and I have an age that is very clearly NOT raining, yet the wings act as if it is. Also, the above two also apply to this world.

**Comment by XCompWiz** [comment]
I'm not sure how the NEI weather toggles work, but the command should work for a little bit.

I don't know about the Zelda mod at all. I'm not surprised there is one, but I don't think I knew of it.

Here the issue may be how it is checking for rain. It's possible to query the Overworld rain status from any dimension. Doing this on clients can get odd.

What versions of Forge are you using? There was a fix for weather packets going to the wrong places and confusing clients. You should already have it, as it was a while back, but just to confirm.

**Comment by Zsashas** [comment]
As far as I know, the NEI weather toggle uses the command to work.

Here's the ZSS mod: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293190

Basically the Song of Storms starts or stops rain, with a cooldown of a minute normally, in the current dimension.

I'm using Forge 1448.
