### ISSUE TITLE
NEI Creative Support?

### ISSUE THREAD

**Issue by Bloodmorphed** [XCompWiz/Mystcraft-Issues#134]
There is an issue with our normal creative mod, These portfolios aer quite annoying without creative lol. Anyways, trying to do it the hard way and just opening a lot of sealed notebooks but I've been doing it for a couple hours and no void world page. Creative+ support would be amazing, if possible.

Thanks!

**Comment by heldplayer** [comment]
Does [this](http://minecraft.curseforge.com/mc-mods/228923-nei-mystcraft-plugin) help you in any way?

**Comment by XCompWiz** [comment]
Held has made an NEI plugins and Mystcraft has the prebuilt collections in the normal Creative menu.
That should hopefully cover everything. :)
