### ISSUE TITLE
Creative book item conflict

### ISSUE THREAD

**Issue by BrokenHearted2** [XCompWiz/Mystcraft-Issues#136]
I am using 1.7.10-0.12.3.00, if I get one of the creative books, like the All symbols book, if I pull one of the symbol pages out I get a random item from another mod. Like right before posting this I got a PCB from PneumaticCraft. What could be causing this and how do you fix it??

**Comment by Dmitchell94** [comment]
I am also having this problem and am getting a AE2 Color Modifier for some reason

**Comment by XCompWiz** [comment]
I'm going to ask some questions based on having seen (and fixed) this issue before.
Are you playing on a server? Does this happen in single player?
Are you getting the folders from the creative menu or out of NEI?

**Comment by Dmitchell94** [comment]
I am playing in single player and I did spawn the folder in from NEI

**Comment by BrokenHearted2** [comment]
Single player here and getting mine from the creative menu. The only way I have found to kind of fix it is disable the mod, open the world up, close out and enable the mod and let it gen new configs, but that is a pain to do if you already have worlds you have made.

**Comment by XCompWiz** [comment]
Odd.
Do either of you have any mods that play with item ids?

**Comment by BrokenHearted2** [comment]
Not that I am aware of, http://pastebin.com/WjxnkpPZ here is a list of all the ones I am using. Maybe you will see one jump out that could be causing it.

**Comment by XCompWiz** [comment]
You closed the issue, but didn't post why. Any feedback? Did you figure out the issue?
