### ISSUE TITLE
Can't pre-profile?

### ISSUE THREAD

**Issue by xJon** [XCompWiz/Mystcraft-Issues#141]
As a modpack maker, I like to use Mystcraft's "pre-profiling" option to reduce the lag when first creating singel-player worlds.
After a lot of time, I updated mods and wanted to pre-profile Mystcraft again to get the required files.
Unfortunately, using Mystcraft v0.12.3.01 and v0.12.3.00 (which known to work for me before), I can't get it to work. The bar is stuck, and even in the log, there's no progress shown.
Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/8945347/11763472/34f9a558-a114-11e5-8466-338e9066497f.png)
What's weird is the black background. Normally it should show a normal Minecraft world, as I remember.
Here's the fml-client-latest.log file: http://paste.ubuntu.com/13975792/
Again - worked before; removed a mod, updated a lot other mods - not working.

Thanks! I hope I didn't miss anything stupid.

**Comment by xJon** [comment]
Thanks to @bochen415 I found out I had to update NotEnoughResources to support Forestry v4.2.x.
Updating the mod fixed my profiling issue.

**Comment by XCompWiz** [comment]
Glad you figured it out. :)  I wonder why it was able to get stuck at that point, though, and not report failure elsewhere.  Did "Back to Title Screen" just take you to the main menu?

**Comment by xJon** [comment]
Well, *as far as I remember*, yes
