### ISSUE TITLE
crash while profiling

### ISSUE THREAD

**Issue by TheAtomicPanda** [XCompWiz/Mystcraft-Issues#142]
i added ExtraTic, enchantingplus, projectE, and treecapitator and it works fine with just enchanting+ and projectE but as soon as i add Extratic it starts profiling again and the game crashes on worldgen of the profiling world..

http://pastebin.com/A5SM0D0n

**Comment by Zsashas** [comment]
ExtraTiC adds molten metals, doesn't it? Each of those would have a page added for it.

**Comment by XCompWiz** [comment]
Zsashas is right as to why the baseline system kicks back on.

As to the crash, it happens in Vanilla; there is no mod code even in the stack shown.  Unfortunately, that means the line numbers are off and I can't see what was null.
It looks like the game crashed as the client connected to the server, though.

Did you figure out this issue? Is it still relevant?
