### ISSUE TITLE
Void and island worlds hang.

### ISSUE THREAD

**Issue by HarroldSaxon** [XCompWiz/Mystcraft-Issues#143]
When generating chunks in any void or island world, the server hangs and becomes unresponsive. log output simply stops without revealing anything. The end and other mod added void worlds are unaffected. 
   I suspect a modification to terrain generation to be the culprit and will report back once I know more.

**Comment by heldplayer** [comment]
This sounds like a problem with a mod trying to generate in the world and getting into an infinite loop. Most likely not a Mystcraft issue but rather an issue in a different mod that Mystcraft brings to light.

**Comment by HarroldSaxon** [comment]
I agree that this is most likely another mod implementing something incorrectly, i'm posting the issue here as it only appears in ages, Dimdoors and aether had no problem wehn i droped them in to see if i could recreate the issue in a non mystcraft dimension. 
   Once I find the offending mod i'll create an issue with them and link it here.

**Comment by HarroldSaxon** [comment]
I've run into a problem while trying to find the responsible mod(s). the issue is clearly caused by multiple mods interacting, but it dosn't seem to be a specific combination. Someone's mod dosn't like other mods terrain additions, but only when generating mystcraft void or island ages. @_@

**Comment by HarroldSaxon** [comment]
Finaly found the incompatible mod! The Diversity mod is causing the issue with his structure generation. I left a comment on his thread, but it looks like it'been a while since he's been active. shttp://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2470440-diversity-alpha-1-6-1-new-villages-new-structures

**Comment by XCompWiz** [comment]
My heartfelt appreciation and thanks for putting forth the effort to track down the root of the issue.  I'm sorry I wasn't around to help.
Hopefully you found a solution. :)

**Comment by HarroldSaxon** [comment]
4"3e
