### ISSUE TITLE
Fatal error loading world, games does not crash kicks me back to main menu.

### ISSUE THREAD

**Issue by banana01** [XCompWiz/Mystcraft-Issues#145]
After making a new age the game crashed and now when i try to load into that world I get a fatal error and get kicked to main menu. The game crashed when i entered that age. Running 34 mods total.

Latest
[latest.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/75857/latest.txt)
Crash report from making age
[crash-2015-12-31_22.47.03-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/75858/crash-2015-12-31_22.47.03-server.txt)

**Comment by XCompWiz** [comment]
I take it you closed this as you realized it was an OutOfMemoryError (OOM) and just increasing the amount of memory you gave to Minecraft fixed it. :P
At least, I hope it fixed it.
