### ISSUE TITLE
Crash to desktop when entering age

### ISSUE THREAD

**Issue by Chessus** [XCompWiz/Mystcraft-Issues#146]
Hi, I usually crash to desktop when entering a new age but it is fixed after I reload my game. After making a random age (v11.0.00) and crashing as usual, my game now crashes when I load my save. Here isw the log from the last 2 attempts

http://paste.ee/p/uaS8o

http://paste.ee/p/7W9XV

**Comment by dmodoomsirius** [comment]
The paste.ee's are not found/ please repost them.

**Comment by XCompWiz** [comment]
This issue appears abandoned. Hopefully resolved elsewhere.
