### ISSUE TITLE
Suggestion: Collation Folder

### ISSUE THREAD

**Issue by Zsashas** [XCompWiz/Mystcraft-Issues#147]
Shift-clicking pages should put them at the end of the folder. Currently, they have to be placed in one-by-one, which is especially tricky when placing them in a new row. This would make it much faster. Also, the A-Z sort button does nothing.

**Comment by KosmosPrime** [comment]
Technically a collation folder and symbol portfolio both have infinite capacity, so I think (because collation folders are a lot cheaper and you get one when opening a sealed notebook) that this is intentional.

**Comment by Zsashas** [comment]
Does the portfolio have the above-mentioned behaviour?

**Comment by KosmosPrime** [comment]
I just checked, you can shift-click pages into a portfolio, you can put an entire collation folder into it and it's contents are always sorted by alphabet. You can't shift click pages out of a symbol portfolio though.

**Comment by Zsashas** [comment]
Sounds good.
