### ISSUE TITLE
Invalid agedata generated

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#148]
We got this agedata on Reika's dev server. It's flawed.

At the end of the agedata, in the section where random populators are, is
biome 43
Tendrils

So it looks like a biome is being generated as a modifier to tendrils.

The oddity? The biome name is "skylands" -- it's an unused biome defined by ChromatiCraft

My thought: Can the generator want to generate a skylands, and an un-specified tendril, and the skylands turns into a loose biome?

[agedata_35.dat.zip](https://github.com/XCompWiz/Mystcraft-Issues/files/107615/agedata_35.dat.zip)

**Comment by XCompWiz** [comment]
I actually have a symbol named "Skylands."  My guess is the biome being added is adding in a remapping rule to convert "Skylands" into "Biome43".  That remapping rule generation was added a long time ago to support moving from named biomes in the age data to biome ids.
So actually the grammar generated a "Skylands" symbol that got remapped.

I'll remove the remapping rule generation, as it's unlikely any agedata files which used such biome references are going to be used on a current version of Mystcraft.

Weird bug! But easy to fix!  I like this kind of bug! :P
