### ISSUE TITLE
Suggestion: Potion ID Whitelist

### ISSUE THREAD

**Issue by Zsashas** [XCompWiz/Mystcraft-Issues#149]
To allow adding potion effects to instability. Should have an auto-blacklist for anything containing "heart" "heal" "instant" or "soul" for sanity reasons.

Alternately, support for a select few mods' effects (some of them anyway) such as Witchery, Ars Magica, Botania, and/or Thaumcraft.

Specific effects I had in mind: 
TC: flux flu, deadly gaze, sunscorned
B: crimson shade, vanity's emptiness
AM2: gravity well (if this is even a potion effect)
W: overheating, insanity, fear, sinking

These are just examples of course. The second method would probably be best, as it would avoid the possibility of having effects like Instant Health/Damage, Combustion (explode when hit), or Polymorph as ambient effects in ages.

**Comment by XCompWiz** [comment]
An interesting idea, but I already have an API for such things.  After the instability rewrite I'll look at supporting more flexibility via IMC.
