### ISSUE TITLE
Crash with Mystcraft world

### ISSUE THREAD

**Issue by frenchiveruti** [XCompWiz/Mystcraft-Issues#150]
It seems that the crash is cause by a BoP biome, but I don't really know.  
[crash-2016-02-01_12.49.00-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/112501/crash-2016-02-01_12.49.00-server.txt)  
I hope it helps!

**Comment by heldplayer** [comment]
This looks like a bug in Botania.

**Comment by frenchiveruti** [comment]
Huh... Well, in case it does something, the world had Jungle, savanna and Higlands center biomes, and it created a world with 257 blocks of height, so the poor botania maybe wanted to place some flowers on the dirt, and failed horribly.

**Comment by heldplayer** [comment]
Yeah, might be related to that, I suggest reporting this on the [Botania issue tracker](https://github.com/Vazkii/Botania) so Vazkii knows about it.

**Comment by XCompWiz** [comment]
Hopefully resolved. If the issue was created on Vazkii's tracker, please either link to this issue from there or link to that issue from here so we can follow what happened. :)
