### ISSUE TITLE
Odd behavior with "Natural Grass/Foliage Color" pages and BOP biomes

### ISSUE THREAD

**Issue by EyeDeck** [XCompWiz/Mystcraft-Issues#154]
I'm using the BOP Mystic Grove biome for testing here because it's reasonably distinctive, but this happens with other BOP biomes too.

Natural Grass Color page specified: http://i.imgur.com/9sDjFRD.png
No grass color page: http://i.imgur.com/Jvbr1Bq.png

With a Natural Grass Color page, vanilla grasses look correct, but BOP grasses are heavily tinted towards a vanilla oceany-looking color. Without any grass color page specified at all, grass color is correct to the overworld version of the biomes. The same effect applies to foliage color as well.

This may well be BOP's fault, since other biome-adding mods seem to display the correct colors (Twilight Forest for one) with the Natural Grass Color page, but why do the correct colors show without any grass color page at all?

**Comment by XCompWiz** [comment]
Did you get your pictures backwards?  Looks like Natural Grass Color is doing its job.

**Comment by EyeDeck** [comment]
Ah, Mystic Grove is supposed to have a funky grass color:
http://biomesoplenty.wikia.com/wiki/Mystic_Grove
For some reason Natural Grass Color overrides it and sets it to a "normal" looking color. It's been a while, but I probably chose Mystic Grove since it demonstrates better than most biomes how off the color is.

**Comment by XCompWiz** [comment]
Natural Grass Color shifts the grass color towards vanilla normal grass color. It's doing precisely what it's supposed to. :)
If it's not the vanilla color then BOP is tinting their blocks a bit in addition to the biome grass color. That's all.  This looks like expected behaviour. :)
