### ISSUE TITLE
Early deck effects should not affect mobs

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#155]
So I was realizing that we have things like "enemy regeneration" or "enemy resistance" in the early decks for "The natives of this place are used to the changes, but you are not".

Well, by that thinking, the other effects like poison, hunger, etc, should not affect native mobs.

Basically, all the negative effects in the first decks should only affect the player.

**Comment by XCompWiz** [comment]
I don't even know that any of these effects will transition through the instabiltiy rewrite.  They've never been that interesting, are mostly just annoying, and can be easily beaten with other mods. I plan to take a very different tactic with instability.

But fair point! :D
