### ISSUE TITLE
1.9 version

### ISSUE THREAD

**Issue by LuciusV** [XCompWiz/Mystcraft-Issues#158]
Hello! Is there any plan for releasing 1.9 version?

**Comment by XCompWiz** [comment]
Updates will follow after I've caught up and fixed some things.  There will probably be a few features I build first before updating as well.  I'm out of the loop and not sure what MC versions are prevalent, but will decide on versions later.

**Comment by DatrixTHLK** [comment]
1.10.2 is prevalent right now  atm but I'll let you do your thing.
