### ISSUE TITLE
[1.7.10]Server crashes on terrain gen, Mystcraft or BoP possible cause

### ISSUE THREAD

**Issue by Lyl4c** [XCompWiz/Mystcraft-Issues#160]
http://pastebin.com/dRaxmJ2S

1.7.10
Forge 10.13.4.1614
mystcraft 0.12.3.02
140 mods / modded multiplayer

Upon logging into a fresh multiplayer modded server; the server will crash within a few minutes. Server will run fine with no players online.

**Comment by XCompWiz** [comment]
The crash is occurring in the baseline profiling system.  Easiest solution might be to just let it finish before generating other chunks. There is a flag in the configs for auto-kicking players while the baselining system is running.   It should only need to finish once on a specific configuration of mods (so you probably stopped seeing this issue already).

I expect 1.8's improved dimension generation threading will fix this (at least I hope so), so it will go away entirely after Mystcraft updates. :)
