### ISSUE TITLE
Archivist Villager Duplication bug

### ISSUE THREAD

**Issue by Eidelmaim** [XCompWiz/Mystcraft-Issues#163]
https://www.youtube.com/watch?v=_N8eCjUABIs&feature=youtu.be

not sure how this is happening, we are on FTB Infinity Evolved 2.5.0 (dedicated server) running Mystcraft version 1.7.10-0.12.3.01.

**Comment by XCompWiz** [comment]
Super packs always have some fun issues. :P
I've gotten a report of some other issues with the villager GUI. It's hopefully related to those, so hopefully fixing them will correct this issue.

The big question is: Are those items real or client-only?

**Comment by Eidelmaim** [comment]
They are very real !!!!

**Comment by XCompWiz** [comment]
Hopefully fixed when fixing #124.

**Comment by Eidelmaim** [comment]
I see you have replaced your code in issue #124, when I have enough time to download our server from our dedi I will test it when you release your update.

**Comment by Eidelmaim** [comment]
I meant issue #156 :)

**Comment by XCompWiz** [comment]
Thanks :)

**Comment by Eidelmaim** [comment]
Hey xcomp, i finally got around to testing this on my bukkit server, sorry this took so long, but i can confirm Mystcraft 1.7.10-0.12.3.03 resolves this issue.
