### ISSUE TITLE
Report of /tpx into profiling dimension

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#164]
Iari reported in IRC that it was possible to /tpx into the profiling dimension.

Then, with no handler, the client crashes.

**Comment by XCompWiz** [comment]
It's not possible with my TPX, but other mods might provide other teleportation commands.

With an actual crash log I could maybe figure out what happened, but it shouldn't be possible to fully enter the profiling dimension.  Getting close should TPX you to the ejection dimension.

Closing until more info can be provided. I can't possibly do "John said this happened" bug reports.
In the future, please have the person who said this make the bug report. :)
