### ISSUE TITLE
Two "FeatureMediumDummy" pages appearing in a random age

### ISSUE THREAD

**Issue by Flameminer221** [XCompWiz/Mystcraft-Issues#165]
I created a completely random age with only a leather and a linking panel, and the resulting age had instability (surface poison). This was surprising since there weren't any block modifiers that appeared to cause instability, but using an NBT editor I found that there were two "FeatureMediumDummy"/Lacking Medium Features symbols (which, according to the wiki, causes instability), and I was told that this was a bug (that there shouldn't be two in the first place) and I should report it here.

Here is a copy of the age data file in question:
[MystcraftBuggedAge.zip](https://github.com/XCompWiz/Mystcraft-Issues/files/340186/MystcraftBuggedAge.zip)

**Comment by XCompWiz** [comment]
Two is perfectly valid.  Excessive, but valid. :P

I'll fix it so that the dummies take up the entire rule chain for the feature set they expand, so you won't get them and anything else in that size category.

**Comment by XCompWiz** [comment]
OK, I *think* these new grammar rules should fix this. :P  Will be in the next release.
