### ISSUE TITLE
Rainbow Rendering Incorrect?

### ISSUE THREAD

**Issue by ReikaKalseki** [XCompWiz/Mystcraft-Issues#167]
Since 1.6 for me - I distinctly remember seeing part of a rainbow in the sky in one age, though at the time had no idea what it was - rainbows appear not to have not rendered correctly. Instead of an actual rainbow, I get a thin, monochromatic (and slightly varying with camera state) line across the sky. I thought this was a case of needing multiple pages for a rainbow or something, but having asked @keybounce, apparently not.

This is what I get:

![](http://i.imgur.com/gDg3Lpc.png)
![](http://i.imgur.com/yLeGif5.jpg)
![](http://i.imgur.com/BsJIqUM.jpg)
![](http://i.imgur.com/IeryMp7.jpg)

I am on a AMD Radeon HD 6850 in the latest Forge, if that matters.

**Comment by XCompWiz** [comment]
It's the AMD cards that do it, and I have never figured out why.  There's a config option to change how the rainbow is rendered which makes it work on AMD cards.  That render method is slower, but looks right on AMD cards.

**Comment by ReikaKalseki** [comment]
I assume "Fast Rainbows" is the one?

The only thing it appears to change is using a GL list, which I know works, since *chunks* are rendered in such a manner.

**Comment by XCompWiz** [comment]
And yet turning off fast rainbows fixes the AMD rendering.  This is why I haven't been able to puzzle out what's different or why it won't work that way on AMD cards. *shrugs*  The flag exists because the bug has come up before.

**Comment by ReikaKalseki** [comment]
I am not sure if this is helpful, but I - a few weeks back - upgraded my GPU drivers (ostensibly for (this)[https://www.reddit.com/r/EliteDangerous/comments/64wtlh/horizons_ctds_less_than_five_seconds_into_launch/]), and it made the fast rainbow option work. I am using a different pack now (and Myst version, for that matter) than the now-year-old post, but maybe that might of help?

**Comment by XCompWiz** [comment]
Thanks for the heads up! :)
I expect rainbows will get revised a lot in 1.11.2, so we'll see what happens.

**Comment by XCompWiz** [comment]
This is probably fixed now.
