### ISSUE TITLE
Looking glass and Vivecraft don't work together.

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#173]
Vivecraft is a mod that supports a VR headset.

When both Vivecraft and Looking Glass are used together, the result is a loss of the GUI and general non-functional-ness.

Discovered by Lightwave. I'll see if he can give you more details.

**Comment by XCompWiz** [comment]
This does not come as a surprise.  This is also the wrong repo.
https://github.com/XCompWiz/LookingGlass

**Comment by keybounce** [comment]
Whoops. I'm just so used to thinking of this as Mystcraft :-).
