### ISSUE TITLE
Specific World Keeps crashing, wondering why?

### ISSUE THREAD

**Issue by Ruthless-One** [XCompWiz/Mystcraft-Issues#175]
I was playing for about a week on my server, with no issue. Then started doing some mystcraft and found my world wasnt working, saw this error (http://pastebin.com/hVaVd6GP). I reverted my world back 2 days, problem was fixed, then a day later, same problem. I reverted back again by about 12 hours, and same problem. but with a "fresh" restore to when the world was working. but the error still exists. Any ideas?

**Comment by XCompWiz** [comment]
That warning is pretty normal and likely unrelated to your world "not working."  Can you give a more specific characterization of what went wrong?  And perhaps a full log?

**Comment by Ruthless-One** [comment]
The mystcraft world i had made, would suddenly stop working, i would click the book and try to go into the world, but nothing would happen, and in the console of the server this error ( http://pastebin.com/qt83ZdqX ) would keep poping up everytime i would click it. and the world would not load. I remember it also saying it could not find the biome, or something like that.

**Comment by XCompWiz** [comment]
Sounds like the server is hanging trying to generate the world. Looking at your error, it seems to be an error in ChickenBones' chunkloader.  The ticket request is erroring.  You'll need to ask there.

**Comment by Ruthless-One** [comment]
Ah ok. Thanks.
