### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DarkXFast** [XCompWiz/Mystcraft-Issues#176]
[crash-2017-02-06_18.18.27-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/755197/crash-2017-02-06_18.18.27-server.txt)

**Comment by XCompWiz** [comment]
Bam. Alakazam.

I'm not downloading a text file; put it on pastebin or something.
You must include something about what you were doing at the time.

**Comment by DarkXFast** [comment]
http://pastebin.com/n24cKiW3

**Comment by XCompWiz** [comment]
My recommendation: Wait for the profiling to finish before playing. There's a flag you can turn on in the configs to share the profiling across all saves, that will do the profiling before you are allowed to play. Use that.

Next time you want to post a bug report, actually give a bug report, please.
