### ISSUE TITLE
Crystals have inconsistent light levels

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#178]
(NB: Tested in a pack with mods that do ASM.)

So today, I ran into mystcraft crystal outputting a light level of about 10 (11?) if there was a torch next to them that was broken.

But left to do lighting recalculations, and the light level emitted dropped to around 6 or 7.

This inconsistency gave me dark spots :-).

Version 12.3.3

**Comment by heldplayer** [comment]
Might be a quirk of the Minecraft lighting system interacting with properties of the block (isOpaqueCube, isSolidBlock, etc..)

**Comment by XCompWiz** [comment]
Sounds like a Minecraft lighting bug to me. I couldn't reproduce, either.
