### ISSUE TITLE
[Request] The Developaws cape

### ISSUE THREAD

**Issue by Developaws** [XCompWiz/Mystcraft-Issues#179]
> If you want to design a custom Mystcraft cape I can look into it. :P

Coming soon™.

**Comment by heldplayer** [comment]
Looking at [this support page](https://help.mojang.com/customer/en/portal/articles/1590522-minecraft-commercial-use) you will see that it is not okay for users to be given custom capes for free or for payment.

**Comment by Developaws** [comment]
> the Commercial usage guidelines state that you may sell cosmetic items, except for “capes”

Except the fact that several hundred mods offer capes, e.g. optifine, for developers of the mod :P If capes wasn't allowed, how come minecraft/forge has the `EntityPlayer#playerCloakUrl` function.

**Comment by heldplayer** [comment]
> Please note that not all features in this article are available in the unmodded version of Minecraft and that most things (except for “capes”) are okay to offer for free or for soft currency.

Furthermore in [this blog post](https://mojang.com/2014/06/lets-talk-server-monetisation/) (which is about server monetisation) also says

> There is one exception to this rule - capes! We have a lot of fun making cool capes for extra-special members of our community and Minecon attendees. We’d like to keep them as exclusive as possible. So, yeah, no capes please, even if you’re giving them away for free.

Now, seeing as this post is targeted at servers you could argue that it does not apply in this case, and you're probably right. However it does highlight that Mojang really does not want random people to have a cape without their permission.

Regarding the `EntityPlayer#playerCloakUrl` function (which I cannot find anywhere), that will most definitely be for internal usage only meaning mods should not be using that.

**Comment by XCompWiz** [comment]
First discussion on this twitter thread seems to specifically declare mod capes a no.
https://twitter.com/Marc_IRL/status/486655146072748032
Sorry.

And I can't find a cape-related mod hook in 1.11.2 either. Only an unused event flag for whether to render it.

**Comment by Developaws** [comment]
I guess we can make a Mystcraft hat though :O

**Comment by XCompWiz** [comment]
You bet. :D
