### ISSUE TITLE
1.11.2 - Issues with Galacticraft chunk mapping

### ISSUE THREAD

**Issue by silent-mobious** [XCompWiz/Mystcraft-Issues#180]
Really excited to see the new update!!!  I added it to my existing modpack and created a new world. 
 Galacticraft does some chunk mapping whenever a server is created, and it appears the updated Mystcraft has some issues with that.  [Details on process.](https://wiki.micdoodle8.com/wiki/Sponge) It crashes the server with an "Already decorating!!" error during that process.  Once I take Mystcraft back out it works properly, and once I start a new server without Galacticraft then Mystcraft works properly.  Anything that can be done to have them play nicely together?

**Mod Versions tested:** Mystcraft 1.11.2-0.13.0.00, Galacticraft 1.11.2-4.0.0.114
**Forge version used:** forge-1.11.2-13.20.1.2414-universal
**Log:** [Pastebin of complete errors](https://pastebin.com/E8PHjUVV)
[00:24:56] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.terraingen.PopulateChunkEvent$Post@23689c52:
java.lang.RuntimeException: Biome [Venus Flat] threw an error while populating chunk.
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_185931_b(ChunkProviderMyst.java:139) ~[ChunkProviderMyst.class:?]

Thanks a lot!!

**Comment by drakray** [comment]
Came for the same bug https://pastebin.com/XAK2WgWR

**Comment by XCompWiz** [comment]
See #188.  I'm changing the baselineing biome selection so that this shouldn't be an issue after the next release. :)
