### ISSUE TITLE
No spawn platform in new ages (1.11.2)

### ISSUE THREAD

**Issue by koril-k** [XCompWiz/Mystcraft-Issues#184]
Hello,
I installed the newest mystcraft version (great work!) and created my first two random ages (no symbols, link panel only). The worlds generated and I could enter them, but both were lacking the spawn platform. In the first world i spawned upon a tree. In the second world I spawned in the sky and fell endlessly. Now I dont dare entering any new ages...
Greetings

**Comment by XCompWiz** [comment]
Huh. I'll investigate. I thought that they were generating correctly, but they might have gotten broken later on during the updating process.  Thanks for the report! :)

**Comment by XCompWiz** [comment]
Looks like a variable was swapped in the update, so the platform was being cleared rather than the area above it.  I've fixed it for the next release. Thanks again! :)
