### ISSUE TITLE
Crash that might be connected to this mod

### ISSUE THREAD

**Issue by Sunconure11** [XCompWiz/Mystcraft-Issues#187]
https://pastebin.com/QMCtDEBU

This crash related to chests has happened to me with mystcraft installed on 1.11.2. Does mystcraft do anything with chests that could cause this?

**Comment by heldplayer** [comment]
Looks like a problem with chests updating recursively during generation or manual placement. Would be weird for Mystcraft causing this, unless some generator got messed up during the update.

**Comment by XCompWiz** [comment]
I think the chunk coord fix fixed this.
