### ISSUE TITLE
Rainbow crash in 1.11.2?

### ISSUE THREAD

**Issue by WolfieWaffle** [XCompWiz/Mystcraft-Issues#189]
I got this crash report, it looks like it was caused by rendering a rainbow. It might be caused by interaction with other clientside mods, but Mystcraft seemed to fail first in the stacktrace (if I'm reading it right) so I assumed the problem would be fixable from this side.

https://pastebin.com/46pLtJ74

**Comment by XCompWiz** [comment]
Thanks for the report! :) We'll check out the rainbows, then.

**Comment by XCompWiz** [comment]
HellFire seems to have already figured this out.  Should be OK in the next release. :)
