### ISSUE TITLE
Game Crash when trying to go to a Mystcraft dimension caused by a mod

### ISSUE THREAD

**Issue by umut25** [XCompWiz/Mystcraft-Issues#192]
Edit by HellFirePvP: *snip* to gist
https://gist.github.com/HellFirePvP/904f36a176ce65b50d0ba3606ba8a41c

Can you fix that conflict

**Comment by HellFirePvP** [comment]
Seems to be rather on Forestry's end than on Mystcraft's.

**Comment by XCompWiz** [comment]
Yup. Looks like Forestry trees.

**Comment by umut25** [comment]
Will you fix this?

**Comment by Urrurrual** [comment]
I recommend also posting an issue to the forestry github, you can find it here: https://github.com/ForestryMC/ForestryMC/issues

**Comment by mezz** [comment]
Forestry is crashing when it looks up what trees can spawn in the biome. It has a biome cache that is generated from all the biomes in the biome registry.
I suspect that the biome here is not in the biome registry when the cache is built, causing Forestry to crash when it looks up the biome.

**Comment by HellFirePvP** [comment]
Keeping a registryKey/ResourceLocation reference of the biome instead of the object itself and querying by resourcelocation from the biome in-world would fix this when the next release comes around.

**Comment by mezz** [comment]
Sounds good, should be resolved in the next version. https://github.com/ForestryMC/ForestryMC/commit/b2e1b2dc9be37f9bc3160eb63f21c45587d28f4c

**Comment by Urrurrual** [comment]
Small issue with the fix. Mystcraft is out for 1.11.2 You pushed the fix for 1.12

**Comment by mezz** [comment]
Thanks, I have backported the fix to 1.11.2 now.

**Comment by HellFirePvP** [comment]
The latest 1.11.2 version of Forestry has the change now as i saw and the next Mystcraft update will handle it properly so this is resolved with the upcoming Mystcraft update and the latest 1.11.2 Forestry version.

**Comment by XCompWiz** [comment]
Should be the current Mystcraft build does it correctly, already, as the fix when into the last release. :) The current Forestry build and the current Mystcraft build should work happily, now. :)
