### ISSUE TITLE
Abandoned libraries not populating?

### ISSUE THREAD

**Issue by michaeljcoffey** [XCompWiz/Mystcraft-Issues#193]
I've visited 11 ages now and explored most of them from 500, 500 to -500, -500 and have yet to see one.

All but one were random ages (only linking panel in the book binder).  In one I used a couple of symbol pages.

**Comment by HellFirePvP** [comment]
It indeed seems like that, i'll investigate.

**Comment by HellFirePvP** [comment]
Issue for it found and resolved for the next update.

**Comment by XCompWiz** [comment]
Thanks for reporting it! :D
