### ISSUE TITLE
Black ink fluid block does not properly display/exist in the world

### ISSUE THREAD

**Issue by heldplayer** [XCompWiz/Mystcraft-Issues#195]
### Steps to reproduce:
1. Run /setblock ~ ~ ~ mystcraft:fluidblockblackink

### What is expected:
A black ink block appears on my feet, allowing me to swim in it.

### What happens:
Nothing is visible, I cannot see the black ink nor can I swim up in it. The only clue of its existence shows when it knocks over torches or tall grass when it is flowing.

**Comment by HellFirePvP** [comment]
A ink fluid block is not obtainable except for setting it manually into the world via commands.

Nevertheless, a proper model will be assigned to it if another mod (Looking at you RFTools) decides for whatever reason to randomly spawn it.

**Comment by HellFirePvP** [comment]
Properly fixed for the next release
