### ISSUE TITLE
Writing desk TESR item scaling is off

### ISSUE THREAD

**Issue by heldplayer** [XCompWiz/Mystcraft-Issues#197]
Between 1.7.10 and 1.11.2 the way items are rendered changed quite heavily. I think even between 1.10 and 1.11 there were changes to this, so quite easy to miss.

Anyway, here's a [comparison between the 2 versions](https://ss.heldplayer.blue/7e5qeKL8).
You can see that in newer versions the book looks about tripled in size, and slightly hanging over the edge of the writing desk.

**Comment by HellFirePvP** [comment]
Fixed/Changed/Properly adressed for the next version.
