### ISSUE TITLE
Linking books use name of the save instead of name of the dimension when creating

### ISSUE THREAD

**Issue by heldplayer** [XCompWiz/Mystcraft-Issues#198]
### Steps to reproduce
1. Craft an unlinked linking book.
2. Turn the unlinked linking book into a linked linking book by right clicking while it is in your hand.
3. Observe the name of the linked linking book.

### What is expected
The name of the linked linking book takes the name of the dimension I'm in.
Examples:
- Overworld
- Nether
- End
- The First Age (Mystcraft age name)

### What happens
The name of the linked linking book takes the name of the save I'm playing.

**Comment by HellFirePvP** [comment]
Fixed for the next update
