### ISSUE TITLE
Any chance of a 1.10.2 port?

### ISSUE THREAD

**Issue by InjuredWolf** [XCompWiz/Mystcraft-Issues#199]
Was wondering, would it be possible to get a 1.10.2 port of a stable release? I don't expect it to be maintained past that if it happens, but if a single port of it could be done, that would be swell.

**Comment by Goten87** [comment]
will be nice to have yeah ^^

**Comment by XCompWiz** [comment]
I can only offer a "maybe" once the mod is stable for 1.11.  At that point we might look a one-off backport.

It is worth mentioning that I do not think this is likely, and that I think the modder community would prefer I didn't reinforce 1.10, but instead updated to 1.12.

**Comment by Crocodail** [comment]
Some mods work for both 1.10.2 and 1.11.2 why not for that mod? So I mean I can download 1.11.2 and it works for 1.10.2

**Comment by InjuredWolf** [comment]
Because a lot of (mainly newer) mods used McJty's CompatLayer mod, but for some older mods, or mods that do finicky things, the effort required to implement that would be not worth. And maintaining 2 versions of a mod is a pain. Does CompatLayer allow 1.12 support yet?

**Comment by Darkmega18** [comment]
I would actually enjoy said 1.12 update, as I'm making a modpack all about dimension jumping, and having this back for 1.12 would be an amazing addition for my modpack's list, and as such, I'd be able to test it while playing and look for bugs that crop up as we go. :)

**Comment by Xorbah** [comment]
I'd much rather prefer 1.12.2. You guys need to stop clinging to 1.7.10 and 1.10.2.

**Comment by daPoseidonGuy** [comment]
Just giving my extra 2 cents, I'd prefer a focus on 1.12.2 as well.

**Comment by erubianwarlord** [comment]
Please just one port for 1.10.2 the majority of mods are for it and 1.7.10 for a reason

**Comment by Xorbah** [comment]
The desperation is real. He has no reason to go backwards to give you a port to 1.10.2, and the majority want 1.12.2. Also, you're wrong on the majority of mods being on 1.10. Statistically, more people play 1.11 and 1.12 now. As for 1.7.10, quite a few of those mods were left behind because the amount of work that it took to update past 1.8+ wasn't worth it to many.

**Comment by CJoe51** [comment]
Don't know his, but he can help you for getting yours out if you ask nicely so you can see actually the modders are the ones clinging to old versions. True, 1.7 might be quite old, but half of the mods I tried don't have 1.12 support as of right now, and all of them are taken from Tekkit list. Also 1.10.2 seems like a anchorpoint for mods as far as I can see so it's not very wise to not to make one working on it. It indeed is a desperation, but not in the way you think. So please think twice before incriminating someone.

**Comment by bookerthegeek** [comment]
Y'all need some chill pills.

It will be updated to whatever version is current when the update to the mod starts, maybe to move onto the next if the update take a while and maybe a backport.

All in all stop your bellyaching and realize the honey catches more flus then spoiled milk.

@XCompWiz whatever you do, I look forward to it on whatever version you release it on. Keep up the amazing work whenever you get around to it.

**Comment by macks2008** [comment]
While I'm a little disappointed 1.10 was skipped in the first place, given the general consensus surrounding it, I agree with Xcomp's initial reply. It would probably be better to just keep moving forward. In the meantime, RFTools is sufficient for most things of the "custom dimension" nature, and there's at least a few other mods that add portals like the Link Portals this one has. Case in point: Draconic Evolution's dislocater portals.

**Comment by Kitsune-Ultima** [comment]
I'm making a map based on the game this mod is based on (Myst ~~~Hexalogy~~~ {Myst, Riven, Exile, Revelation, URU, End of Ages} _hold that thought Cyan may be releasing more Myst-like games in the near future_) and having an update for 1.12.2 (even 1.13) would make my life much easier.

**Comment by 3TUSK** [comment]
https://reddit.com/r/feedthebeast/comments/8l30tm/mystcraft_just_updated_for_112/

Considering the fact that more mods are available on 1.12.2, can this issue be closed?

**Comment by InjuredWolf** [comment]
probably, yeah
