### ISSUE TITLE
[1.11.2][Loot Bags Incompatibility]

### ISSUE THREAD

**Issue by superninjakiwi** [XCompWiz/Mystcraft-Issues#200]
Loot Bags causes a crash on startup in conjunction with this mod. 
http://paste.atlauncher.com/view/de07cd9e

The error report seems to indicate that the crash is due to a lack of a page ranking system.

https://github.com/Malorolam/LootBags/issues/77

**Comment by heldplayer** [comment]
Looks like an issue with the order FMLPostInitializationEvent gets fired for Mystcraft and Loot Bags. Mystcraft builds the page rankings during that time, and Loot Bags is doing something with loot tables during the same time.

A way to solve this would be to add a soft dependency for Mystcraft to be after Loot Bags, or Loot Bags to be after Mystcraft.

**Comment by superninjakiwi** [comment]
For ease of access: 
Maloraam:
From what I can see, the issue is that I trick minecraft into temporarily loading the loot tables during post-init instead of server start, which is triggering the Mystcraft code to ask it's database about the pages, but that database hasn't been initialized yet, so it's throwing the errors.I tossed an after:Mystcraft dependency on there as a test and the issue still happens, so I don't know if there's anything I can do to allow for the problem to resolve cleanly. Best I can figure I can do is simply set up an hardcoded blacklist for Mystcraft pages from the dungeon loot sources, but that means no pages will show up in bags unless they're whitelisted in. XCompWiz could probably set up some handling on his end to just give a default treasure weight if that error pops up, which would also fix the problem.
--

**Comment by Malorolam** [comment]
Okay, I've done a bit more work and I had the modid wrong in my code (no idea what mustcraft is, but clearly not the right mod), putting in a dependency solves the issue.  This'll get fixed on my end in the next version.
