### ISSUE TITLE
Ink Mixer bug, Mystcraft version 0.13.1.00 (untested for 0.13.2.00, please assist)

### ISSUE THREAD

**Issue by Knightcoreframe** [XCompWiz/Mystcraft-Issues#204]
Placing an ink mixer does not use the item (as though in creative, even when in survival), and the image on the hot bar can disappear as well (interacting with a usable object such as the placed mixer or a chest will cause the image to return). Trying to pick up a dropped ink mixer will crash your game and the world will be unusable (I don't World Edit to see if I could remove the item from my inventory and fix it, sadly I learned this bug the hard way). Burning or letting the dropped ink mixer despawn, having placed one or not, will not cause an issue. I can provide my mod list if asked by attaching files to a reply. It is completely drawn from Forge and contains 78 mods besides Forge itself (my current Forge version is 13.20.1.2421). I'd like to know if this bug is due to a mod conflict, if it's part of the current version of Mystcraft, and/or if it's just the version I'm using. Any help testing version 0.13.2.00 for this bug would be appreciated.

Thanks for taking the time to review and assist on this!

**Comment by heldplayer** [comment]
Already fixed in 1.13.2.00

**Comment by Knightcoreframe** [comment]
Thanks!
