### ISSUE TITLE
Dimension bug

### ISSUE THREAD

**Issue by Knightcoreframe** [XCompWiz/Mystcraft-Issues#205]
The first time I attempted to access a blank dimension via descriptive book, the game froze. I waited at least ten minutes before I force quit the program via a task manager, then when I relogged I was still in the Overworld with the book on the floor. Further attempts to enter the dimension crash the game. Is this a bug? Or is there something else going on? Currently I have an Aroma1997 Mining Dimension open but have not traveled to any others.

**Comment by dmodoomsirius** [comment]
Can you [pastebin](http://pastebin.com), [Gist](https://gist.github.com/), or use something similar to post the crash report? that will help them see what is causing the error.

**Comment by Knightcoreframe** [comment]
[crash-2017-08-05_23.42.01-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1202863/crash-2017-08-05_23.42.01-server.txt)
I created a second crash to verify it was using the book again, which is attached here. I can provide the original freeze if asked. Sorry for the late reply, I was busy all day

**Comment by HellFirePvP** [comment]
#192 Update Forestry

**Comment by heldplayer** [comment]
Word of advice: if you're reporting bugs, make sure all your mods are updated and if not, update them and check if it still happens.

**Comment by Knightcoreframe** [comment]
Thanks! Sorry about that, I could have sworn everything was updated. The Mod Options list is supposed to tell you but apparently there's still some issues with that.

**Comment by heldplayer** [comment]
Unfortunately, the mod options list only shows updates when the mod author has added support for it in their mod. If you're using the Twitch launcher it'll show which mods have updates if you look at the mod list in the profile, on other platforms I'm not sure.

Thank you for wanting to help out though! :)
