### ISSUE TITLE
Crash on breaking blocks in a Mystcraft dimension

### ISSUE THREAD

**Issue by Knightcoreframe** [XCompWiz/Mystcraft-Issues#206]
Here's all the crash logs I am sure involve the bug. I was using Tinker's tools at the time, and there was a bit of lag but it didn't seem that bad until I broke a block. I can't tell if this was just an incredible amount of lag or something else.

Thanks for any help you can give me with this!

[crash-2017-08-08_01.29.57-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1207187/crash-2017-08-08_01.29.57-server.txt)
[crash-2017-08-08_01.34.43-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1207188/crash-2017-08-08_01.34.43-server.txt)
[crash-2017-08-08_01.42.35-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1207189/crash-2017-08-08_01.42.35-server.txt)
[crash-2017-08-08_01.50.40-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1207190/crash-2017-08-08_01.50.40-server.txt)
[crash-2017-08-08_01.18.01-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1207191/crash-2017-08-08_01.18.01-server.txt)
[crash-2017-08-08_01.23.30-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1207192/crash-2017-08-08_01.23.30-server.txt)

**Comment by heldplayer** [comment]
Looks like an issue with [AntiqueAtlas](https://github.com/AntiqueAtlasTeam/AntiqueAtlas).

**Comment by Knightcoreframe** [comment]
Well...what kind of issue? I don't speak crash report haha. Mystcraft just doesn't like the mod?

**Comment by heldplayer** [comment]
Well it's AntiqueAtlas crashing on something, not sure what but right now I wouldn't say it's an issue on Mystcraft's end.

**Comment by Knightcoreframe** [comment]
Well when I leave my Antique Atlas back in the Overworld, it seems to fix the problem. It's probably the mapping function messing up in some manner. It maps other dimensions just fine, such as Aroma1997's Mining Dimension, but I guess Mystcraft is too weird for it. Should I notify the Antique Atlas bug site of this?

**Comment by heldplayer** [comment]
That might be the best, as it's happening in their code.

**Comment by Knightcoreframe** [comment]
Thanks for the help!
