### ISSUE TITLE
Single Biome dimension interaction and crash

### ISSUE THREAD

**Issue by Knightcoreframe** [XCompWiz/Mystcraft-Issues#207]
Multiple mods obviously interact with world generation, but I think Single Biome isn't interacting correctly. While in my Single Biome Mushroom Island (Dirt Block + Standard World generation) dimension, I found a dark area of land under a tendril platform way up in the air that was spawning a lot of hostile mobs. Unable to change the difficulty in the dimension (I don't know if this too is a bug or not, but you can't change the game difficulty while in a Mystcraft dimension), I went back to the Overworld and swapped to Peaceful, then investigated the dark area with F3 mode on. It was all Mushroom Island biome until I actually stepped under the platform. Somehow, a Biomes O' Plenty "Brushland" biome had spawned. About a quarter of a second after reading the biome, the game crashed.
[crash-2017-08-08_02.48.32-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1207232/crash-2017-08-08_02.48.32-server.txt)
Getting back into the game had no issues, but then as the world was loading around me I stepped back out of the Brushland area and checked the F3 mode again. A second or so later the game crashed again.
[crash-2017-08-08_02.55.27-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1207235/crash-2017-08-08_02.55.27-server.txt)

The main issue is the multiple biomes existing in a Single Biome world, which I assume is just a lack of compatibility in terms of world generation. But the crashes also concern me. Are they just lag? Or is there more at work?

Thanks for all the help!

**Comment by heldplayer** [comment]
Looks like the same issue as #206
