### ISSUE TITLE
[1.7.10] Using mystcraft linking book in same dimension crashes game

### ISSUE THREAD

**Issue by TheLastSpectre** [XCompWiz/Mystcraft-Issues#211]
When creating a mystcraft linking book in the overworld, and using it, the world appears to unload, with chunks disappearing until the screen goes light gray, with the game closing soon after. This does not happen with only mystcraft installed, so I assume it must be because of other mods I have installed. I will attempt to upload the log at a later date, as my internet is too poor to upload it all in one go, and it crashes pastebin if I attempt to paste it there.

**Comment by InjuredWolf** [comment]
What's your mod list? unlikely the issue will be fixed on this side (1.7.10 support is gone, afaik). I might be able to help you find the issue. Crash log in pastebin would be great

**Comment by TheLastSpectre** [comment]
Sorry about the late response, it seems the issue was connected to my usage of the mod NotEnoughIds, which appeared to be causing the problem. I will continue to test further until I am certain.

**Comment by XCompWiz** [comment]
Going to close this unless more info comes to light. Also, 1.7.10 won't be getting further updates.
