### ISSUE TITLE
Symbol Assignment Logic

### ISSUE THREAD

**Issue by Mace134** [XCompWiz/Mystcraft-Issues#212]
Apologies if this has been discussed previously, but how does Mystcraft decide which blocks to _create_ symbols for? I can not be certain if this is a bug or a feature but there doesn't seem to be a symbol for some vanilla blocks and Mystcraft also seems to skip over Forestry ore blocks.

**Comment by XCompWiz** [comment]
Mystcraft automatically detects most fluids, but doesn't search for normal blocks.  Normal blocks are added manually or by other mods via API.

If you want to discuss which blocks should get symbols, come join us on the Discord. :D https://discord.gg/pRGH45W
