### ISSUE TITLE
MystCraft World Lighting Issues

### ISSUE THREAD

**Issue by stevegriffiths** [XCompWiz/Mystcraft-Issues#215]
I am having some lighting issues with MystCraft worlds. I'm not sure if this is a MystCraft bug, Minecraft bug, or something else. I am using MystCraft with the Minecraft Forge loader 1.11 and no other mods.

The lighting in all my  MystCraft worlds looks like this: 
https://drive.google.com/file/d/0B7LilNqMUh09X1p3TnFGNUtuWHc/view?usp=sharing

Namely: 
* Always very dark on the horizon 
* Dark patch around the sun 
* Strange yellow and red block lighting occurs around horizon at dawn and dusk respectively

Lighting in the over world is fine.

These are my symbols and config for the world (from NBTExplorer) - there's nothing I can see here that would be causing the problem: https://drive.google.com/file/d/0B7LilNqMUh09eGpOeWhaX1lKSjQ/view?usp=sharing.

**Comment by InjuredWolf** [comment]
quick question, do you have Optifine? or Stellar Sky?

**Comment by stevegriffiths** [comment]
No, I just have MystCraft loaded through Forge loader with no other mods installed. Esentially it's the bare minimum to run MystCraft.

Since my original post I have also tried creating MystCraft worlds from brand new over worlds, just to check if it was an issue with that particular overworld save, and I'm having the same issue in every case.

**Comment by XCompWiz** [comment]
None of this was "lighting" as in the mechanic, but the sky render visualization and colorization.
I think these various issues have been handled better in other issue reports (as multiple issues) and all are fixed by next release, so I'll go ahead and close this one. :)

**Comment by stevegriffiths** [comment]
@XCompWiz amazing, thanks for taking the time to reply and I am looking forwarding to updating and trying out the changes :)
