### ISSUE TITLE
Mystcraft has started error checking

### ISSUE THREAD

**Issue by madmichael2004** [XCompWiz/Mystcraft-Issues#216]
Whenever I try to run my modded game, it crashes. In the crash log it says "Mystcraft has started error checking" and then after that it shows a lot of domain missing textures things when all the mods have the textures with them.

https://pastebin.com/Kmqjt6Cb

**Comment by HellFirePvP** [comment]
at minesweeperMod.client.FieldStatHandler.tickEnd(FieldStatHandler.java:70)

Most likely that minesweeper mod.

**Comment by madmichael2004** [comment]
Thank you. That has fixed the problem I was having.
