### ISSUE TITLE
[1.11.2] Change in selected difficulty

### ISSUE THREAD

**Issue by YukoHoon** [XCompWiz/Mystcraft-Issues#218]
I tend to play on peaceful, mostly because I'm more interested in the gatering resources and building part of the game. Since I started creating Age books I've noticed that the difficulty changes from peaceful to normal without any apparent reason. I haven't been able to discover what exactly was the switch that changes the difficulty, but it seems to happen while loading any world/sub world. It does not only affect the Ages but also the overworld.

**Comment by XCompWiz** [comment]
So entering an age actually changes the difficulty? Or is it just using a linking book? Can you set the difficulty back to peaceful while in an age?

**Comment by XCompWiz** [comment]
I've fixed the issue with dimensions being mishandled by Mystcraft.
There does seem to be a bug where if you load the game in a dimension the difficulty gets set to normal. As far as I can tell, however, that's a Forge bug. It applies to all dimensions, near as I can tell.
