### ISSUE TITLE
Crash with Thaumcraft liquid death.

### ISSUE THREAD

**Issue by MoxieGrrl** [XCompWiz/Mystcraft-Issues#22]
http://pastebin.com/f8dm0bgj

Was worldhopping, as you do. My random descriptive book generated a cave world with liquid death ocean. It didn't go so well, as you see.

**Comment by jinks** [comment]
I ran into the same issue today when generating Crystal Blocks.
Any news on this issues? Not being able to generate Crystal Blocks is obviously quite a showstopper for using MystCraft.

Crash Log: http://pastebin.com/H1mH9QVp

I'm running Modsauce pack with manually added MystCraft, so loads of mods, custom fluids and all that jazz, but the log doesn't seem to reference anything except WorldGenMystCrystalFormation.

**Comment by XCompWiz** [comment]
I'm quite certain this is the same issue as #33. Theoretically the current dev builds shouldn't have this issue.

**Comment by bochen415** [comment]
I really don't want to talk ETA's but are there any plans for a release?
Don't hate me, my DIMS are crashing.

**Comment by XCompWiz** [comment]
heh. No worries. RL has just kind of kicked me, so I've been distracted from Mystcraft.  I may end up pushing a release minus my usual level of rigor...
