### ISSUE TITLE
Do u plan to update Mystcraft to the 1.12.2?

### ISSUE THREAD

**Issue by MadRatSRP** [XCompWiz/Mystcraft-Issues#220]

**Comment by iain-davis** [comment]
I was just wondering how much progress was being made towards updating to 1.12.2.

**Comment by HellFirePvP** [comment]
It runs, that's about it.
Everything is massively broken that dips just a bit into world-creation. I still got a mountain of work before me that i currently don't really have the time to. I'll get some more free time soon-ish so... Yea. That's about as much as i'll say to that.

**Comment by Goten87** [comment]
why is it still not open source so a lot of people can work on it if Xcomp is not working on it anymore :(

**Comment by CurePindal** [comment]
Any  news? Or source release, please?

**Comment by CurePindal** [comment]
Dear lovely Mystcraft! I miss you so much in my magic mod pack on 1.12.2! 
Life is just not the same without you..! =/

**Comment by 3TUSK** [comment]
https://reddit.com/r/feedthebeast/comments/8l30tm/mystcraft_just_updated_for_112/
This issue can be closed now.
