### ISSUE TITLE
Mystcraft crash !

### ISSUE THREAD

**Issue by Vurtek** [XCompWiz/Mystcraft-Issues#222]
I created a descriptive book on a server with my friends , I enter but it crashed. And when I try to go on the server it crashed again ! But the server is fine. Help me please 
[crash-2017-12-30_19.01.34-client.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1594877/crash-2017-12-30_19.01.34-client.txt)

Sorry for my English , i'm french ..
Thanks !

**Comment by XCompWiz** [comment]
No idea, probably too late to be useful now anyway. Sorry about the issue.
