### ISSUE TITLE
Problem with Mystcraft and Advanced Rocketry[1.7.10]

### ISSUE THREAD

**Issue by demycat** [XCompWiz/Mystcraft-Issues#226]
I had a world with the Mystcraft mod, but after adding the Advanced Rocketry mod to the same world, I can not log in anymore, that is, I have to choose (when I create a new world with two mods, then everything is OK)

**Comment by demycat** [comment]
I have logs
[2018-03-30-2.log](https://github.com/XCompWiz/Mystcraft-Issues/files/1863542/2018-03-30-2.log)

**Comment by XCompWiz** [comment]
At a guess, Advanced Rocketry adds a dimension to a specific dim id in the positive range. Fixed dim ids should default to negative numbers to avoid conflicts with existing dynamic dimension mods.
You should be able to change the fixed id in Advanced Rocketry's config.
