### ISSUE TITLE
Mystcraft Crashing server

### ISSUE THREAD

**Issue by Anubite51** [XCompWiz/Mystcraft-Issues#228]
My friend and I have run into an issue with our installation of mystcraft.  Whenever he tries to use a descriptive book and enter it, the server crashes and gives the following crash report.
[crash-2018-04-02_22.21.21-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1869969/crash-2018-04-02_22.21.21-server.txt)

Any insights that could help explain the crashes would be appreciated!

**Comment by XCompWiz** [comment]
Fixed in 0.13.2.01 (for MC 1.11.2).
