### ISSUE TITLE
Writing Desk doesn't drop all items when destroyed.

### ISSUE THREAD

**Issue by Nezumi-chan** [XCompWiz/Mystcraft-Issues#230]
I couldn't find any mention of this anywhere, so I decided to report it here. I... kinda badly botched a decent run of Mystcraft, because I was rearranging furniture and broke my writing desk with an axe. The paper in the right-hand panel all dropped... but not the Symbol Portfolio in the lefthand slots. I tried again to make sure I didn't miss anything, and this time the collation folders I used for testing were all devoured.

**Comment by HellFirePvP** [comment]
Adressed with build for [mystcraft-1.12.2-0.13.4.02.jar](https://minecraft.curseforge.com/projects/mystcraft/files/2564176) 1.12.2
