### ISSUE TITLE
Profiling Locking Up Server

### ISSUE THREAD

**Issue by InsomniaKitten** [XCompWiz/Mystcraft-Issues#231]
I have no idea what is related and what isn't, so here is every issue I found whilst troubleshooting the lockup..

**Mod version:** [1.12.2-0.13.4.00](https://minecraft.curseforge.com/projects/mystcraft/files/2564079)

The server gets stuck generating a structure, which locks up the entire server after a few seconds of profiling.

![trace](https://i.imgur.com/ForJBo1.png)

A copy of a JVisualVM snapshot can be found in the zip below. The trace is on the server thread.

[MystCraftProfileSnapshot.zip](https://github.com/XCompWiz/Mystcraft-Issues/files/2023810/MystCraftProfileSnapshot.zip)

I also experienced log spam from cascading world gen lag, caused by MystCraft and Serene Seasons, which may be related or a seperate issue, not sure.

[CascadingWorldGen.gist](https://gist.github.com/InsomniaKitten/5d9c260a3d7d98beb30b71a22e8e3683)

**Comment by XCompWiz** [comment]
Fixed in 0.13.4.01. :)

**Comment by Gunner76th** [comment]
@XCompWiz Problem here is, according to CurseForge, you dont have 0.13.4.01 out for 1.12.2 You do however have it out for 1.11.2

**Comment by Gunner76th** [comment]
![image](https://user-images.githubusercontent.com/5566872/40326762-6e2bd43c-5d0e-11e8-9291-4a513632b318.png)

**Comment by XCompWiz** [comment]
It just took a little time for CurseForge to update. :)
