### ISSUE TITLE
The Wiki is down, and no alternatives for documentation exist.

### ISSUE THREAD

**Issue by GazbonicAcid** [XCompWiz/Mystcraft-Issues#232]
[The Wiki](http://xcompwiz.com/wiki/) is down, and no alternatives for documentation exist.

**Comment by coldReactive** [comment]
It's been like this for a long time, yes.

**Comment by Darkmega18** [comment]
If in doubt. Direwolf20. shouldn't be too different (or at all different) from there.

**Comment by Nawor3565** [comment]
Just thought I'd add, the new wiki is at [wiki.mystcraft.xcompwiz.com](http://wiki.mystcraft.xcompwiz.com/Main_Page). It's a WIP, but already has a lot of the info needed to get started with the mod.
