### ISSUE TITLE
Cascading Worldgen bringing things to a halt in 1.12.2

### ISSUE THREAD

**Issue by IndigoAvemour** [XCompWiz/Mystcraft-Issues#233]
[Log for formality](https://pastebin.com/Jf4Luywf), but it just says the same thing over and over again:

> [14:45:59] [Server thread/WARN]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> [14:45:59] [Server thread/WARN]: Chisel loaded a new chunk [65536, 0] in dimension -2147483648 (Mystcraft) while populating chunk [4096, 0], causing cascading worldgen lag.

Pretty much the same issues I've experienced with the 1.11 version- framerate is fine and I can move around and whatnot, but mobs don't move and I can't access chests, crafting tables, etc. Though actually as I typed this, things seem to have gone back to normal, ahah. Still gonna post this just to let you know the cascading worldgen thing is still a bit of an issue.

I've loved Mystcraft ever since I discovered it, so I'm stoked to finally play this again. c:

Edit: Okay I spoke too soon, the log says the worldgen is cascading again x_x To ask a question in regards to it, does it work fine to just wait it out or will it continue doing this no matter what?

**Comment by HellFirePvP** [comment]
This specifically refers to another issue which is/was adressed with the release for 1.12.2: 0.13.4.01 and newer versions.

**Comment by IndigoAvemour** [comment]
Right, thank you.

**Comment by IndigoAvemour** [comment]
Small update:

Before updating I looked through the config options and set it to profile during game setup. Everything went much more smoothly after updating to 0.13.4.01, however once profiling was complete the game froze and became unresponsive. After force-closing and restarting the game, though, everything looks good. The effort put into this mod is commendable and I'm now more excited than ever to start on the mod's contents, I'll be sure to document any other troubles I have should I come across them. As the initial issue seems to be fixed, I'll go ahead and close this issue.
