### ISSUE TITLE
No liquid pages created for the Colorful Water, Tinkers Construct or Content Tweaker mods

### ISSUE THREAD

**Issue by TheDeviantCrafter** [XCompWiz/Mystcraft-Issues#234]
Colorful Water adds 32 colored water fluids. Tinkers' adds various molten metals. Content Tweaker adds nothing by default, but can be told to create custom liquids.

None of these are detected by MystCraft. They don't have fluid pages according to JEI, and aren't listed in the symbols.cfg file.

**Comment by HellFirePvP** [comment]
Version 0.13.4.03 that fixed this is released. Closing the issue~
