### ISSUE TITLE
Can't craft Link books

### ISSUE THREAD

**Issue by Darkmega18** [XCompWiz/Mystcraft-Issues#239]
Unless it's changed to work using the bench/mixer/binder in some way or fashion, I recall you'd used to just craft a book into them. but not even JEI is coming up with a recipe so it's either changed and I haven't gotten the memo, or it's broke currently on the mystcraft-1.12.2-0.13.4.02 release. D:

**Comment by heldplayer** [comment]
The recipe for a Link Book is a Link panel combined with a piece of leather if I remember correctly.

**Comment by Darkmega18** [comment]
yeah, I was told by someone else I asked. but I'll try it now when my MC loads. but JEI wasn't showing any recipes at all...

**Comment by heldplayer** [comment]
If you've figured it out, I suggest closing the issue.
