### ISSUE TITLE
Crash with Writing Desk: StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by srs-bsns** [XCompWiz/Mystcraft-Issues#24]
mystcraft-1.7.10-0.11.0.00
http://pastebin.com/NvTmv9yT

While using the writing desk with a non-renameable item such as a link panel or modifier page...
![](http://www.nihilism.ca/~misc/images/20141019-mc-1.png)
...attempts to modify the name by inserting characters results in the name being reset automatically, but if one is fast enough (and/or perhaps has a slow enough computer) and is able to insert >1 characters before the name is reset, it will overflow causing this OOB exception.

**Comment by XCompWiz** [comment]
I think this has been fixed in the most recent build. Thanks again. :)
