### ISSUE TITLE
Linking Books and Descriptive Books Teleport Player to Wrong Location in Survival Mode.

### ISSUE THREAD

**Issue by snakemasterepic** [XCompWiz/Mystcraft-Issues#240]
**Summary**
When using a portal with a linking book or descriptive book, the player is teleported to an incorrect location if playing in survival mode.  This issue does not occur in creative mode.

**Repro Steps**

1. Launch Minecraft 1.12.2 with MystCraft 0.13.4.02 installed.
2. Create a new world for survival mode (with or without cheats).
3. Obtain a descriptive book, a linking book to the overworld, some crystals, and a receptacle.
4. Use the descriptive book to access the new age.
5. Use the linking book to return.
6. Create a portal frame and place a book receptacle in it.
7. Place the descriptive book in the receptacle.
8. Travel through the portal in survival mode.

**Observed Result**
The player arrives away from the initial spawn point.

**Expected Result**
The player arrives at the spawn point.

**Notes**
- The player arrives at the spawn point if traveling through the portal in creative mode.
- Using the books to travel without portals works as expected in both creative and survival mode.

**Comment by SethosSch** [comment]
Came here to post this! Encountered the same problem. Also when trying to steal a mystcraft villager from an age, using a portal, the guy didn't land where he was supposed to land (in fact i couldn't find him in the overworld at all). The portal back to the overworld worked fine for me but not for the multiple entities i've thrown there

**Comment by snakemasterepic** [comment]
After further experimentation, I found that the coordinates the player is taken to are the player's coordinates in the world the player is traveling from, (for example, entering a portal at (32,69,-41) in survival will always spit the player out at (32, 69, -41) in whatever age the portal is connected to.)

**Comment by XCompWiz** [comment]
Sounds like the netcode being derp again. It likes to kick players back to where they were during teleports where they player is moving. The server gets an update packet from the player which sets their position back to where they were, after they teleported. I'll see about sorting it out.

**Comment by DeadSix27** [comment]
I didn't want to open another issue as this seems too similar, but on my end the linking books do not work at all. I can create one in survival and I can set its position (shift right click) but when I open it, clicking the blueish-box on the right page doesn't do anything. (unless this behavior changed from 1.7.10 to 1.12.2)

**Comment by XCompWiz** [comment]
Unrelated issue. Also, are you trying to use the book from within the world you made it? The books don't allow for that.
Either way, if it is a bug, please open a separate issue for it. :)

**Comment by DeadSix27** [comment]
@XCompWiz Was that a different mod adding that feature to mystcraft in 1.7.10? I am very sure that in-world teleportation worked fine there.
PS: Depending on your answer ill open a new issue or see my questions/issues as answered/solved.

**Comment by XCompWiz** [comment]
In-world teleportation is a link property that can be obtained through the ink mixer.
http://wiki.mystcraft.xcompwiz.com/v0.13:Linking#Intra-Linking

**Comment by keybounce** [comment]
Crystal portals? ... One more thing to add to my testing/tutorial world :-). Normal books work just fine for me.

**Comment by Meiestrix** [comment]
Hi @XCompWiz , today I noticed that I have exactly the same problem with version 1.12.2-0.13.7.03.
With game mode everything is fine but in survival you are at the wrong position, when you go through a portal.
Has this not implemented yet?

**Comment by XCompWiz** [comment]
It's a recurring problem. Whenever Minecraft changes their netcode it has a chance of coming back. I've fixed it again, I think. Maybe permanently now.

**Comment by Meiestrix** [comment]
Ok, thanks for your answer.

**Comment by Xiantrius** [comment]
Hi
@XCompWiz
Even when you thought it was fixed, I have the same problem as the previous ones. When the book is on the bookstand it works perfectly. If I use the crystals with the book compartment and put the identical book in the book compartment, then the portal spins around. As soon as I teleport from one position to another.
Funnily enough, the exception is when I am sent through another dimension with the crystal portal, then there are no problems if a player teleports through.
Would you please fix the problem?

**Comment by XCompWiz** [comment]
You have got to be kidding.

Mystcraft 1 is no longer supported. I should close this issue tracker completely. Thanks for the reminder.

**Comment by Xiantrius** [comment]
This is no joke, I'm dead serious.
I think it's a pity and Mystcraft 2 that you started you don't even do for v1.12.2.
I even described the error to you. Still, well you are the developer and decide that, find it sad that you don't fix the problem once and for all before you close the topic. If you think the problem is fixed, that doesn't mean it is. Apparently the will is not there... too bad.
I've decided to look for another mod that has a resemblance and also found one. The developer who makes a mod is much more interested if he already offers to fix the bugs.
