### ISSUE TITLE
[1.12.2] Sun Celestials render incorrectly

### ISSUE THREAD

**Issue by Atrius97** [XCompWiz/Mystcraft-Issues#242]
Using Forge 14.23.3.2676 and Mystcraft 1.12.2-0.13.4.02 (issue persists in 0.13.4.03), all suns, (whether multiple or single sun ages), appear to render in the same configuration as the overworld sun, rising in the east and setting in the west.

The Sunset for these Suns render in the correct direction as specified by the Age grammar, with the sun setting west, and the sunset appearing elsewhere in the sky. All suns for the age appear to lump together in this configuration creating large "sun blobs", but Moon Celestials seem unaffected and appear in the correct direction and configuration.

Example of single sun age, with sunset rendered completely separated from the celestial, with celestial setting in the wrong direction:
![2018-05-27_20 09 07](https://user-images.githubusercontent.com/39707481/40624624-db1bd158-626a-11e8-976d-52e6cd7fd9f6.png)

Example of "Suns Lumping together" with Moons appearing unaffected: 
![2018-05-26_11 36 29](https://user-images.githubusercontent.com/39707481/40624641-fc52825e-626a-11e8-855f-cba56cde0712.png)

**Comment by XCompWiz** [comment]
Sounds like the sun celestial are just rendering like the vanilla sun, perhaps using the wrong position. Amusing that the sunrise is apparently in the right spot, despite this. :D

**Comment by XCompWiz** [comment]
Should be fixed in uploading build (.05)
