### ISSUE TITLE
[1.12.2] Biome Distribution and Generation issue.

### ISSUE THREAD

**Issue by Atrius97** [XCompWiz/Mystcraft-Issues#243]
Using Forge 14.23.3.2676 and Mystcraft 1.12.2-0.13.4.02 (issue persists in 0.13.4.03), Biome distrubution appears to incorrectly assign and generate biome materials and terrain.

Checkerboard biome generation yields several small 4x4 "mini chunks" of different biome materials, but the biome flag for the entire age acts as if it's single biome distribution instead, as the biome does not change when entering any of these 4x4 squares. Examples:
![2018-05-27_19 35 52](https://user-images.githubusercontent.com/39707481/40624815-00799d1c-626c-11e8-9d5c-2aa6c24d68f7.png)
![2018-05-27_19 39 34](https://user-images.githubusercontent.com/39707481/40624829-0a8be206-626c-11e8-932b-1255e9f7ad65.png)

Tiny Biome distribution is similar, but instead has small 2x2 "mini chunks" where the biome flag is set as one of the other biome pages, with the first biome page largely dominating the remaining space. Examples:
![2018-05-27_20 13 20](https://user-images.githubusercontent.com/39707481/40624858-2e94084a-626c-11e8-8ecb-f800583de8bb.png)
![2018-05-27_20 13 27](https://user-images.githubusercontent.com/39707481/40624859-2f9022f6-626c-11e8-9d54-8df3dde509b2.png)

Age Data for both ages:
[Age Data.zip](https://github.com/XCompWiz/Mystcraft-Issues/files/2045838/Age.Data.zip)

As well, certain ages with Nether or certain Overworld biomes (Desert for example), appear to cut entire chunks out of the world. This effect can be observed 16 minutes and 42 seconds into this [Mystcraft Bit-by-Bit instructional video for 1.12.2.](https://youtu.be/uFZGPt7DBlQ?t=16m42s)

**Comment by CurePindal** [comment]
Placement of the libraries is overall a bit wonky right now. The weird cobble platform on one hand and then its very often also floating.

**Comment by XCompWiz** [comment]
Could you please make a separate issue for the library generation? They are unrelated issues, and thus need separate tracking. :)

**Comment by Atrius97** [comment]
Library generation issue moved to new issue: #286
