### ISSUE TITLE
[Suggestion] A Warning on the book binder

### ISSUE THREAD

**Issue by coldReactive** [XCompWiz/Mystcraft-Issues#248]
When adding more than a certain amount of "Accelerated" pages, the age made can cause severe lag, enough that the game cannot actually allow you to get back to the overworld. (And in fact, severely instable worlds actually don't let you move due to stacking slow debuffs. During lag, you can't even double jump in creative mode to fly.)

I would recommend putting a warning when the player attempts to place more than 10 Accelerated pages into a descriptive book that says "Warning: Adding too many accelerated pages can cause client instability, and can cause you to not be able to return to the overworld even with creative mode."

**Comment by XCompWiz** [comment]
I don't feel like that's something I really need to be warning people about. It's clearly obvious abuse, and should be obvious that the extra ticks will cause lag.

More practically, I should just not allow the age to work, and that'll be handled by the instability rewrite.
