### ISSUE TITLE
Crash with Writing Desk: UTFDataFormatException (Overflow/OOB)

### ISSUE THREAD

**Issue by srs-bsns** [XCompWiz/Mystcraft-Issues#25]
mystcraft-1.7.10-0.11.0.00
http://pastebin.com/Ydk7urZd

While using the writing desk with a renameable item, such as a notebook or agebook, attempting to name it with an long string exceeding 2^16 characters results in this exception.

Perhaps the maximum name length for agebooks/notebooks/etc. should be set to something sane like 32 characters, with a check to make sure that entered text can't exceed that length. Anything longer than this seems overly excessive and has undesireable display characteristics:

![](http://www.nihilism.ca/~misc/images/20141019-mc-2.png)
![](http://www.nihilism.ca/~misc/images/20141019-mc-3.png)
![](http://www.nihilism.ca/~misc/images/20141019-mc-4.png)
(Also note that under certain circumstances the cursor can bug out as seen in the third image. I think It depends on a specific position cause by a certain amount of narrow characters in the edit box, such as 'i' or 'l'. You can replicate this by first filling the box with 'i's then typing any other character. This is a minor display bug though.)

**Comment by XCompWiz** [comment]
I think this has been fixed in the most recent build. Thanks again. :)
