### ISSUE TITLE
[1.12.2] Symbol portfolio can't be put in Bibliocraft bookshelf

### ISSUE THREAD

**Issue by Geethebluesky** [XCompWiz/Mystcraft-Issues#256]
As the title says. 

I'm assuming that's incorrect, since Descriptive Books can be shelved.

**Comment by heldplayer** [comment]
This looks more like something Bibliocraft has to fix on their end, as I don't think Mystcraft enables Descriptive Books being shelvable on its own.

**Comment by Geethebluesky** [comment]
Ok, will bring it up there, thanks!

**Comment by Geethebluesky** [comment]
Ok well Nuchaz indicated he'd add support in at a future update! And the word gets around that Mystcraft for 1.12.2 exists. :)
