### ISSUE TITLE
Crash In Writing Desk

### ISSUE THREAD

**Issue by MarshTheBacca** [XCompWiz/Mystcraft-Issues#263]
I was just taking out some pages in my Collation Folder placed on the left side of the UI, then I pulled out one page and my game crashed. I am running a modpack. MarshTheModpack, on the technic platform, so there may be conflicts involved.

The crash report seemed to point to Mystcraft being the culprit
Crash Report: https://pastebin.com/Bguh0JyP

Minecraft Version: 1.12.2
Mystcraft Version: mystcraft-1.12.2-0.13.4.03

**Comment by MarshTheBacca** [comment]
It has crashed another 8 times since, I'm just trying to transfer pages from my main Collation Folder into sub-Collation Folders, like "Colours" and "BIomes" and "Blocks". I can only seem to take out 3 or 4 pages out before the game crashes again. I've noticed that the page I've just picked up before the crash happens, then disappears and I lose that page forever.

**Comment by XCompWiz** [comment]
Looks like a network vs client race condition issue, such that two threads are accessing the same data at the same time. I will need to either add some locking or change the data structure.
The threading must be new in Minecraft GUIs.

**Comment by XCompWiz** [comment]
Duplicate of #247
