### ISSUE TITLE
Fog Color Issue

### ISSUE THREAD

**Issue by B-Butternubs** [XCompWiz/Mystcraft-Issues#264]
I've been using the correct page order (modifier before noun), but I can't seem to remove an inevitable black fog that overrides all of my colour selections. I've tried all the methods and multiple page orderings, but it doesn't seem to fix it, so I think it might be a bug. Mods used: Better Foliage, Dynamic Surroundings, JourneyMap, Mystcraft. Mystcraft Version: Latest (0.13.4.03 for Minecraft 1.12.2)

![2018-07-07_02 10 22](https://user-images.githubusercontent.com/40908522/42407456-f0fd7c26-818a-11e8-8e8f-0502113121e1.png)

**Comment by XCompWiz** [comment]
Have you tried the No Horizon page? I often find it hard to tell what part of the sky is what rendering in Minecraft. :P

**Comment by XCompWiz** [comment]
Turns out it was using void fog at all levels because the factor inverted (or maybe a boolean got lost?). Either way, tracked it down. :) Thanks for the report!
