### ISSUE TITLE
tpx uses wrong height

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#265]
TPX wants to use a height of 64 as its destination regardless of what height it should be at.

Definitely confirmed in the overworld. Oddly, an island world spawned me at 64 as well (but it worked, that's where the spawn platform was).

**Comment by XCompWiz** [comment]
tpx doesn't (shouldn't) set a spawn height by default; linking should deliver you to the world's reported spawn point. So have you observed the world spawn point "to be wrong" here?
How are you determining what the height "should" be?

**Comment by keybounce** [comment]
If I die in the Overworld, I wind up at a certain location at a height of
69. If I TPX into the Overworld, I wind up at the same location at a height
of 64.

**Comment by XCompWiz** [comment]
OK, sounds like the death spawn and the tpx are probably handling that spawn location differently.

When you tpx to height 64 in this case, where do you end up?

**Comment by keybounce** [comment]
The top of a large opening.

Y equals 64 was actually Stone; y equals 63 and below was open air. Trying
to put stone blocks at 63, 62, Etc did not help. I did not try making the
entire vertical column solid. Instead, I just made sure that 64 and 63 were
air, had a torch, and put a trapdoor at the top of 62 so that i would not
fall down.



How do people use tablets, cell phones? The keyboards stinks, voice control
has no ability to correct what it thinks you said, Etc. You can't even
easily position the cursor where you need to go to correct things, and this
is after now 5 days of trying to make this thing work right.

I think I fixed all of the typos. Speakos.

**Comment by XCompWiz** [comment]
Most people don't use voice control, and have become adept at the keyboard, despite the tiny size. It's not ideal.
I wouldn't expect most people to use GitHub from a tablet or phone, but I have no data there.

Thanks for the info!
