### ISSUE TITLE
Click Drag does not work on the right side of a writing desk.

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#271]
Click drag will not take pages out of a folder when the folder is in the right side of the writing desk interface.

https://youtu.be/D3nQ3NAOZsw?t=32m1s

**Comment by keybounce** [comment]
Also happens in the bookbinder.

https://youtu.be/D3nQ3NAOZsw?t=33m50s

**Comment by XCompWiz** [comment]
Seeing as it probably hasn't ever worked, I expect you are in a small minority of people who actually try to click drag items in Minecraft. :P
I'll have to look into it.
