### ISSUE TITLE
There is no way to make "space" in a folder to add in modifiers.

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#272]
With the old "chest" interface for folders, it was possible to put symbols down in such a way that you had room in front of them. This made it relatively easy to make room for additional modifiers, or to prepare 2 or 3 stanzas in a similar manner.

With the new interface, you can not force new space at the end of a book. You can only remove symbols in the middle to create space.

https://youtu.be/D3nQ3NAOZsw?t=37m2s

**Comment by XCompWiz** [comment]
I've changed the surface gui to support dropping pages to any point, so that you can place pages in the black area of a folder and it will pad it out with empty space. I'll see if I can also add a visualization of what it does.

**Comment by XCompWiz** [comment]
Added a visualization and allowed the max scroll to expand based on the padding to your cursor.  Should cover everything you want, I hope.

**Comment by XCompWiz** [comment]
![surface_arbitraryplacement_2018 07 21_16 33](https://user-images.githubusercontent.com/707256/43036133-e1939548-8d03-11e8-86e4-4dc02ddca1d3.gif)

**Comment by keybounce** [comment]
That looks *nice*. Thank you!
