### ISSUE TITLE
Black ink does not block sunlight.

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#277]
Black ink does not block sunlight. You can go swimming in an ocean of black ink and see just fine.

https://youtu.be/D3nQ3NAOZsw?t=1h29m58s

**Comment by XCompWiz** [comment]
Took some hunting (and it's likely that existing ink won't really get "fixed", it seems), but I got the light blocking effect fixed. Also added ink fog and water overlay render.
