### ISSUE TITLE
Incorrect name of Nuclearcraft's nuclear wasteland biome page

### ISSUE THREAD

**Issue by TheDeviantCrafter** [XCompWiz/Mystcraft-Issues#281]
![image](https://user-images.githubusercontent.com/18755309/42425227-c4d5907e-82df-11e8-97db-53b9aca89140.png)

The image should be self-explanatory. The page is named `Page (Nuclear _Wasteland Biome`. That underscore shouldn't be there.

**Comment by XCompWiz** [comment]
heh. Should be easy enough to fix the string format stuff. :P
Though I guess I should check for if biomes have localization built in, now.

**Comment by XCompWiz** [comment]
Basic fix in place. Haven't checked for any form of Biome name localization.
