### ISSUE TITLE
Server crash when specific player joins

### ISSUE THREAD

**Issue by Lewimaron** [XCompWiz/Mystcraft-Issues#284]
Since earlier today our server has been crashing whenever a certain player joins the server. Here is the crash report:

https://pastebin.com/8rkKAtNf

**Comment by Lewimaron** [comment]
I have now deleted that players data files and they can connect without crashing again.

**Comment by XCompWiz** [comment]
Whoops. Looks like I made a bad reference in my DimensionUtils. Sorry about that. Will fix.
