### ISSUE TITLE
Server crashes when player entering new world

### ISSUE THREAD

**Issue by 3TUSK** [XCompWiz/Mystcraft-Issues#285]
Server is running w/ Forge 14.23.4.2732 and SpongeForge 1.12.2-2705-7.1.0-BETA-3291. Let me know if more information is needed.

https://paste.ubuntu.com/p/h3ms5w4MsP/

**Comment by XCompWiz** [comment]
Crashes somewhere in Sponge, so you'll need to report it there and see what they say. :)

**Comment by Aaron1011** [comment]
This should be fixed in the latest SpongeForge

**Comment by Veovis-Muaddib** [comment]
Cool, thanks for the heads up!

Is there a link to a particular commit or message, out of curiosity?

**Comment by Aaron1011** [comment]
There were several different issues. If you're interested in looking at commits, start with https://github.com/SpongePowered/SpongeCommon/commit/312c8c991d159a5ddfb109d0dd0f3cdfed1210cd, and work your way backwards

**Comment by Veovis-Muaddib** [comment]
Thanks, much appreciated for both the links and the efforts to resolve these issues.

**Comment by 3TUSK** [comment]
Just did a quick test, and I confirm that using SpongeForge 1.12.2-2705-7.1.0-BETA-3383 alongside with Forge 1.12.2-14.23.4.2747 and `mystcraft-1.12.2-0.13.6.00.jar` does solve the issue. Should we wait for more test results before we close this issue ticket?

**Comment by Veovis-Muaddib** [comment]
Can close this one for now, when there's a confirmation we can also close the other one.

If the same crash occurs, please reopen this issue with the crashlog.  If another crash occurs, please open a new issue and include the new crashlog.
