### ISSUE TITLE
[1.12.2] Library structures generating incorrectly.

### ISSUE THREAD

**Issue by Atrius97** [XCompWiz/Mystcraft-Issues#286]
Libraries seem to generate very strangely in the new update, having massive horizontal cobblestone platforms below them. Example: 
![2018-05-27_19 35 04](https://user-images.githubusercontent.com/39707481/40624938-a7e9f7cc-626c-11e8-9406-c61a6b561b48.png)
This occurs at ground height for most worlds, but for island and void worlds, the cobblestone platform seem to extend about 4x the standard platform size along the X/Z axis, and is only one block vertically, causing them to "float" at the height they'd usually be generated at, (sans cobblestone pillar.)

Example: I don't have a personal example for this, but the effect is observed 17 minutes into this [Mystcraft Bit-by-Bit instructional video for 1.12.2.](https://youtu.be/uFZGPt7DBlQ?t=16m42s)

**Comment by keybounce** [comment]
Hmm, I didn't open a report for this one? Sheesh, I missed one :-).
