### ISSUE TITLE
[0.13.5.01] Incorrect Slot Assignment in Writing Desk slots 2, 3, and 4

### ISSUE THREAD

**Issue by Atrius97** [XCompWiz/Mystcraft-Issues#288]
With only Mystcraft 0.13.5.01 installed, I cannot place or shift-click folders or portfolios into the Writing Desk in slots 2 through 4. The inventory seems to act as if they're unable to receive folders/portfolios.

Slot 2 seems to accept vanilla Paper, but only a single sheet.
Slot 3 seems to accept Ink Bottles, but they do not empty into the writing desk when placed in Slot 3.

I've including the bug's effect in this gif:
![gif](https://user-images.githubusercontent.com/39707481/42855876-c596885c-89ff-11e8-9794-bd41875fb220.gif)

**Comment by Veovis-Muaddib** [comment]
I'm seeing this bug on 0.13.5.01, but not on 0.13.5.00.

**Comment by XCompWiz** [comment]
I changed the way the inventory handling worked (to fix the issue with placed items not updating) and it broke the filtering id ordering. :P I've got a fix for next release.
