### ISSUE TITLE
Client side worlds not updating total world time properly

### ISSUE THREAD

**Issue by tterrag1098** [XCompWiz/Mystcraft-Issues#29]
Any call to world.getTotalWorldTime() on the client world returns 0. This does not replicate vanilla behavior and breaks a lot of mods. An example can be seen in #19 (this issue has since been fixed with a workaround).

**Comment by fnuecke** [comment]
This still seems to be an issue in 0.11.0.00.

Note that I use this for animation only (mainly to pause said animations when the game is paused, but have it work if daylight-cycle is disabled).

A case where this *is* used in vanilla Minecraft is the animation of a beacon's beam. This animation is also broken in Mystcraft ages.

**Comment by XCompWiz** [comment]
I think everything should work now in 0.11.1.  Verification would be nice.

**Comment by fnuecke** [comment]
Can confirm it's working now, thanks!
