### ISSUE TITLE
[1.12.2] Twinkling Stars are non-functional, several random layers of Normal Stars take their place.

### ISSUE THREAD

**Issue by Atrius97** [XCompWiz/Mystcraft-Issues#290]
Twinkling Stars appear not to generate even when adding Twinkling Stars page in place of Normal Stars.

Pages used:
**Purple Color, Twinkling Stars,
Blue Color, Cyan Color, Twinkling Stars,
Blue Color, Twinkling Stars,
 Purple Color, Blue Color, Twinkling Stars**

Normal Stars can be identified easily as they do not flash, and are rendered above the Moon Celestial layer in the skybox.

Effect observed in Mystcraft 0.13.5.0-01:
![42913766-fd2162d8-8ab3-11e8-94c9-8fd60c4942d0](https://user-images.githubusercontent.com/39707481/42914043-64322236-8ab5-11e8-9ecf-360b9110e77a.png)
![untitled](https://user-images.githubusercontent.com/39707481/42914044-655d4cd0-8ab5-11e8-8caf-d2de7f172b30.png)
![untitled2](https://user-images.githubusercontent.com/39707481/42914045-66186b28-8ab5-11e8-88c1-33c94755feb4.png)

Age Data for affected age:
[agedata_2.zip](https://github.com/XCompWiz/Mystcraft-Issues/files/2211551/agedata_2.zip)

**Comment by XCompWiz** [comment]
The sky is full of blending (not diamonds, despite popular information), which means that stars and the moon kinda blend together all the time. You can see the stars through the moon, or on top of the moon, depending on who rendered first, and that's a little arbitrary, I think.

Either way, the twinkling stars symbol is currently ignoring the gradient passed to it and the alpha for it's star layers, so the twinkling is broken. Should be fixed next release.
