### ISSUE TITLE
Mystcraft 0.13.5.02 really does not like Quark

### ISSUE THREAD

**Issue by ItsTheKais** [XCompWiz/Mystcraft-Issues#291]
After updating to the latest Mystcraft, I went into an age I had made previously, which uses the Natural Grass Color symbol, and got this crash, which seems to involve Quark's greener grass feature: https://pastebin.com/AfXRJCsj

So after restarting Minecraft, I went into the mod configs to turn greener grass off, but as soon as I tried to open Quark's config screen, I got a different crash, which also seems to be between Quark and Mystcraft: https://pastebin.com/xYd629sD

I then disabled greener grass right in the config file and tried logging in once more, and I got the first crash yet again.

Finally, I reverted back to Mystcraft 0.13.5.01, which allowed me to view Quark's config screen and log back into the save with no problems.

Mod versions involved:

* Forge: 1.12.2-14.23.4.2725
* Mystcraft: 1.12.2-0.13.5.02
* Quark: r1.4-125

**Comment by laneyfamily** [comment]
2nd'd, getting this error: 
[https://paste.dimdev.org/befapuyiro.mccrash](url)

**Comment by XCompWiz** [comment]
Oh, cool, I'm not the only one using this trick. :D
I see exactly what happened here. I'll have it fixed by the next build. :)
