### ISSUE TITLE
[0.13.5.03] Moon Celestials "Sunrise" and "Sunset" don't align with Moon position.

### ISSUE THREAD

**Issue by Atrius97** [XCompWiz/Mystcraft-Issues#292]
This bug was observed in an Age with two moons, and their "Moonrise and Moonset" colors appeared to render in the opposite direction to their position. 

### Moon "Sunset", Being Rendered South, other Moon below horizon and not responsible for effect:
![2018-07-20_23 48 59](https://user-images.githubusercontent.com/39707481/43032601-53b412a6-8c78-11e8-9fcd-9fd3a7926b2c.png)

_Probably related to #242._

**Comment by XCompWiz** [comment]
Turns out, the moon was rendering in the wrong spot, not the sunrise. :P
This time it wasn't the angle being used wrong, but the moon being inverted (like the vanilla moon render). Just a basic copy error when updating.
