### ISSUE TITLE
Mystcraft tooltips don't re-render on shift change

### ISSUE THREAD

**Issue by Veovis-Muaddib** [XCompWiz/Mystcraft-Issues#294]
Vanilla tooltips allow for hiding information until shift is pressed, at which point more information is revealed.  I'm not sure if they re-render every frame or if they re-trigger on specific keypresses.

I'm checking `net.minecraft.client.gui.GuiScreen.isShiftKeyDown()`, but there may be an event for GUI keys.

Sorry to post this right after you refactored to make them not re-render every frame. :P

https://gitlab.com/veovis.muaddib/mystcraft-info/issues/4

**Comment by Veovis-Muaddib** [comment]
I set it to show a counter every time the event runs, looks like it definitely runs every frame:

![image](https://user-images.githubusercontent.com/2359968/43041468-d1df2584-8d1e-11e8-984b-37d7c7169528.png)

**Comment by XCompWiz** [comment]
Really? Minecraft tooltips recalculate every frame?  Eesh.
Well, easy enough to conform to, I guess. I can just undo what I did to make it only render the once.

**Comment by Veovis-Muaddib** [comment]
Thanks, sorry about the back and forth.  Enables this though:

![2018-07-22_10-14-36](https://user-images.githubusercontent.com/2359968/43047697-7f3da632-8d98-11e8-993d-1a6e9c7f262f.png)

![2018-07-22_10-14-41](https://user-images.githubusercontent.com/2359968/43047698-808db2f2-8d98-11e8-9016-5bd97b141382.png)
