### ISSUE TITLE
Meteor explosion crash on server 

### ISSUE THREAD

**Issue by Seiklus** [XCompWiz/Mystcraft-Issues#313]
[](https://pastebin.com/HdEQbEji)

I walked into a random Mystcraft cave dimension and upon getting to y level 128, several effects were bestowed upon me and my server had crashed due to meteors. above is the linked crash

**Comment by SnoaKitten** [comment]
This also Occurred for me as well
[crash-2018-09-15_12.22.40-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2385686/crash-2018-09-15_12.22.40-server.txt)

**Comment by Zoryn4163** [comment]
Also happening here
[crash-2018-09-24_23.54.12-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2414714/crash-2018-09-24_23.54.12-server.txt)
