### ISSUE TITLE
Question: Is there a way to add pages for other mod materials added to the world after Mystcraft?

### ISSUE THREAD

**Issue by DwellerBenthos** [XCompWiz/Mystcraft-Issues#316]
Here's the situation, I play on a server with a custom pack that includes Mystcraft. After initial server start, we decided to add Extra Planets for Galacticraft. The thing is, pages for the blocks and other materials added with Extra Planets don't exist for Mystcraft, I presume because Extra Planets was added at a later date, or that the the mods aren't compatible, but I doubt that, it seems Mystraft can add pages for almost anything.

So the question is, is there way to tell Mystcraft to scan the current mod list and create pages for all new materials it finds, preferably without messing up the pages and ages already created? I looked on the wiki under commands and didn't see anything that seemed relevant.

**Comment by TheFloydman** [comment]
*Mystcraft* automatically adds biomes and fluids it detects from other mods, but not blocks. However, you can use CraftTweaker to add any block (including vanilla blocks) as a *Mystcraft* Page. Follow the instructions at http://wiki.mystcraft.xcompwiz.com/v0.13:CraftTweaker. Be careful: You will need to specify how often the page shows up as loot (cardRank or CRank), how often the page is chosen to satisfy unspecified grammer (categoryRank or GRank), and what the block can be used for (for example, you might want it to be valid for structures, but not for the entire ground).

**Comment by TheFloydman** [comment]
Also remember to change the variable *newBlockSymbol* if you are adding more than one block.

**Comment by DwellerBenthos** [comment]
Ah, OK thanks, that's probably beyond what the server admins want to spend time doing as not a lot of players care otherwise.

**Comment by HellFirePvP** [comment]
I'll mark this as done as the question is resolved.
