### ISSUE TITLE
[CRASH] Server crashed on creating explosion

### ISSUE THREAD

**Issue by matix931** [XCompWiz/Mystcraft-Issues#319]
Forge: 1.12.2-14.23.4.2765
Mystcraft: 1.12.2-0.13.6.00

Unstable world with double dense ores modifiers caused server to crash.

log: [crash-2018-10-23_21.43.03-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2507776/crash-2018-10-23_21.43.03-server.txt)
stacktrace:

> java.lang.NoSuchMethodError: net.minecraft.world.Explosion.<init>(Lnet/minecraft/world/World;Lnet/minecraft/entity/Entity;DDDFLjava/util/List;)V
> 	at com.xcompwiz.mystcraft.explosion.ExplosionAdvanced.toExplosion(ExplosionAdvanced.java:194)
> 	at com.xcompwiz.mystcraft.explosion.ExplosionAdvanced.doExplosionA(ExplosionAdvanced.java:113)
> 	at com.xcompwiz.mystcraft.entity.EntityMeteor.newExplosion(EntityMeteor.java:180)
> 	at com.xcompwiz.mystcraft.entity.EntityMeteor.onImpact(EntityMeteor.java:156)
> 	at com.xcompwiz.mystcraft.entity.EntityMeteor.func_70071_h_(EntityMeteor.java:99)
> 	at net.minecraft.world.World.func_72866_a(World.java:1993)
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
> 	at net.minecraft.world.World.func_72870_g(World.java:1955)
> 	at net.minecraft.world.World.func_72939_s(World.java:1759)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by RGBoorman** [comment]
I just got this issue with an unstable word caused by diamond ore spikes - this is on the December release.

**Comment by TheFloydman** [comment]
It's not dense ores; it's meteors. Meteors are known to cause crashes. You should disable the meteor page in Mystcraft's symbols.cfg. That is the only fix currently available.

**Comment by RGBoorman** [comment]
This also disables it being added randomly to an age? No worries, will do that.

Personally, I was only correlating it to the diamond ore in that it causes instability and instability can result in explosions. 

edit: And done. I've set it to no meteorites in instabilities.cfg as well.

**Comment by Veovis-Muaddib** [comment]
Yeah, there's an instability effect and a symbol for them, looks like you've found both.
