### ISSUE TITLE
[Feature request] Adding more block pages through the config file

### ISSUE THREAD

**Issue by matix931** [XCompWiz/Mystcraft-Issues#320]
Would be great if there will be ability to add some custom block pages for world generation, for example: Silver Ore Block, Copper Ore Block etc.

**Comment by HellFirePvP** [comment]
Doable through crafttweaker integration.

mods.mystcraft.CTAgeSymbol.createBlockSymbol(String word, IBlockState ctBlockState, int cardRank) returns a mods.mystcraft.symbol.CTBlockSymbol

mods.mystcraft.symbol.CTBlockSymbol.addCategory(String modidCategory, String category, int categoryRank)
Adds a category. Check the com.xcompwiz.mystcraft.api.symbol.BlockCategory api documentation for available categories.

Finish the symbol creation with
mods.mystcraft.symbol.CTBlockSymbol.register()

**Comment by HellFirePvP** [comment]
Also, here: http://wiki.mystcraft.xcompwiz.com/v0.13:CraftTweaker
