### ISSUE TITLE
Console World Coord Spam

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [XCompWiz/Mystcraft-Issues#325]
![image](https://user-images.githubusercontent.com/25037295/48762810-ccf45d00-ece6-11e8-9c72-bffcfa623240.png)

**Comment by Pythonic-Rainbow** [comment]
A new image shows even worse stack dump
![image](https://user-images.githubusercontent.com/25037295/50398185-92cc1e80-07b0-11e9-9807-c4c54908ec31.png)

**Comment by TheFloydman** [comment]
This last one is not Mystcraft's fault. It is a Mystcraft dimension (the profiling dimension, to be exact), but Recurrent Complex is causing the cascading worldgen lag.

**Comment by Pythonic-Rainbow** [comment]
@TheFloydman even the stack trace isn't Mystcraft's fault?

**Comment by Veovis-Muaddib** [comment]
It's happening during profiling, which means it wouldn't happen without Mystcraft installed.

Cascading alerts are fine in small numbers, but if they're happening a lot or you're noticing slowdown then it's a problem.

The second crash log is a different issue, I'm fairly sure that disabling Galacticraft biomes should resolve it.

**Comment by Veovis-Muaddib** [comment]
Forgot to mention: If the profiling stage is causing slowdown (or crashes) you have two options:

1. Wait for it to finish, there will be an in-game alert and a console message telling you it's done.  Obviously doesn't work if it's outright crashing, but works great for slowdown.  You only need to profile once per world.
2. Disable profiling.  This will make mod-added symbols (think liquid metals for instance) incredibly powerful unless you go in and add a custom instability value for each of them in the configs.  However, you can also just disable mod added symbols that you think would be overpowered, disable profiling, and be done.

**Comment by Pythonic-Rainbow** [comment]
How to disable profiling?

**Comment by Veovis-Muaddib** [comment]
Here you go: http://wiki.mystcraft.xcompwiz.com/v0.13:Instability#Profiling

**Comment by Pythonic-Rainbow** [comment]
Thanks, in that case it will no longer be an issue. Closing
