### ISSUE TITLE
[1.12] Portals with intra-linking books broken

### ISSUE THREAD

**Issue by ghost** [XCompWiz/Mystcraft-Issues#330]
Made a portal, put an intra-linking link book in the receptacle, portal turns on. When I try walking in, I'm taking to the location my linking book is set to, but only for a split second and then I'm taken back to infront of the portal. I'm on single player.

Latest versions of everything, mc 1.12.

**Comment by TheFloydman** [comment]
Could you kindly explain why you closed the issue?
