### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by renadi** [XCompWiz/Mystcraft-Issues#332]
So, I've got a couple issues, I hope related.

Mystcraft 1.12.2-0.13.7.02
Forge 14.23.50.2796

First, when starting this world I found a house with 2 Mystcraft books in  it hidden behind a bookcase with a button, one ??? Descriptive and one that said something like Abandoned Study.  

I've played for a while and just realized I can turn rotten flesh into leather in my pack so I did that and made a linking book, then I tried to visit one of these two ages.

What happened first is Mystcraft threw an error in the upper right, pressing CTRL+I Said I could continue playing but it would likely cause world corruption.

I tried anyway, then while trying to load the age it crashed with the following error: https://paste.dimdev.org/axabanucov.mccrash

Subsequent loads result in this error: https://paste.dimdev.org/iqogiqiqat.mccrash

I'm not certain this is even a Mystcraft error as it mentions other mods(Recurrent Complex, Hammer Core, and Dynamic Trees)  but figured I would ask here first unless you can shed insight about who it should be reported to.

Update:
Just tested on a new world and this is the error  I get, it specifically mentions Dynamic Trees.
https://paste.dimdev.org/redutoriwi.mccrash

**Comment by TheFloydman** [comment]
The Abandoned Studies in the overworld are from More Mystcraft, and add-on mod. The ??? book with blank pages is a descriptive book. The other book is a linking book that leads back to the study. I don't think More Mystcraft is to blame, but I thought I should let you know you don't have to create an additional linking book.

**Comment by TheFloydman** [comment]
Also are you playing a specific modpack?

**Comment by Veovis-Muaddib** [comment]
Can you try disabling biomes from Recurrent Complex in the symbols config file?

Another possibility at a glance is that Recurrent Complex might be indexing an array with a signed value.

I'm not sure on either of those as I'm skimming the log from mobile.  I just see that there is a negative 1 being passed as an index for biomes, and RC is mentioned toward the end.

Of note, the call stack seems really deep and repetitive, and I'm wondering if there's also some cascading world gen going on.

**Comment by renadi** [comment]
I didn't know RC messed with biomes, I'll take a look when I get home, if
it doesn't that's not my intention.

And right now this is a bit of a personal Modpack, it's Harsh Magic on
curse, but with all the mods updated for testing, just not released because
of various issues and wanting to finish up recipes before I update the
curse page.

**Comment by Veovis-Muaddib** [comment]
I don't know for sure if it does, I was just reading the logs on a narrow screen in a bit of a rush, and that jumped out as a possibility.

**Comment by renadi** [comment]
The only reference I see to biomes in RC is this config:

    # Biome Expression that will be checked for every single structure. Use this if you want to blacklist / whitelist specific biomes that shouldn't have structures. [default: ]
    S:universalBiomeMatcher=

Doesn't seem relevant.

**Comment by renadi** [comment]
https://github.com/ferreusveritas/DynamicTrees/issues/190#issue-394837781
Potentially related issue, sounds like it's happened to someone else.

**Comment by Veovis-Muaddib** [comment]
Good find, that should actually help track down the issue.  Looks like terrain generation doesn't know what biome it's is generating for.

**Pure speculation**, but that might be the way world gen worked early on in Minecraft before they switched, and Mystcraft still does it that way because nothing (until now) broke because of it.

**Comment by HellFirePvP** [comment]
Seems to have been solved on DT's side. Reopen if that's not the case please.
