### ISSUE TITLE
Using linking books or the /tpx command breaks the vanilla `F3 + N` shortcut to cycle from spectator to creative mode

### ISSUE THREAD

**Issue by TheDeviantCrafter** [XCompWiz/Mystcraft-Issues#333]
When you join a world for the first time in creative mode with op permissions, you can press F3 + N to switch to spectator mode. When you enter a Mystcraft world, this breaks until you leave the world and come back. You can still switch using commands, but if you try to use F3 + N, it says "[Debug]: Unable to switch gamemode, no permission."

I can confirm that this happens in multiplayer as well, although I don't know if you need to relog or restart the pack to fix it. Switching from spectator to creative has the same issue. It also continues to be a problem even if you leave the Mystcraft age. Simply being in one for any amount of time causes the bug.

**Comment by TheDeviantCrafter** [comment]
It appears that the act of traveling to a Mystcraft dimension causes the bug. I logged out in a Mystcraft age, restarted the pack, and when I came back I was still in the age. I was able to use F3 + N to switch to creative mode.

The bug also triggered when I used the `/tpx` command to teleport out of the Mystcraft dimension to the overworld.

Closing the world and opening it again fixes the bug in singleplayer. I don't have to restart the entire pack.

**Comment by TheDeviantCrafter** [comment]
Actually, this appears to be an issue with the `/tpx` command, not with teleporting to or from a Mystcraft age. I think Mystcraft adds the `/tpx` command. I was able to trigger the bug by teleporting from the overworld to the nether.

Using a linking book to teleport from the overworld to the nether also triggers this bug.

**Comment by HellFirePvP** [comment]
Related to #340 most likely.
