### ISSUE TITLE
[1.12.2] Null Pointer Ecxeption

### ISSUE THREAD

**Issue by Draskh** [XCompWiz/Mystcraft-Issues#335]
This happens in single player world. Cannot join anymore after removing SecretRooms and OpenBlocks.
[crash-2019-01-23_17.25.12-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2788209/crash-2019-01-23_17.25.12-server.txt)
[crash-2019-01-23_17.27.43-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2788210/crash-2019-01-23_17.27.43-server.txt)

**Comment by Draskh** [comment]
I cannot even create a new world.

**Comment by TheFloydman** [comment]
Wonky stuff can happen whenever you remove mods in Minecraft, especially if the ones you remove do more than just add blocks. Were you in a Mystcraft dimension when you last disconnected?

**Comment by Draskh** [comment]
No. I just tried to go in my creative world. I cannot even create a new world. I had this bug also with an older version, but the world was 4 month old so I did not report that. This is actually the same issue now.

**Comment by Draskh** [comment]
Even the disconnection is confusing because I join a single player world.

**Comment by TheFloydman** [comment]
Can you provide a crash report from single player?

**Comment by Draskh** [comment]
The crash reports a from single player.

**Comment by Draskh** [comment]
Removing mods should also never effect creating a new world.

I have a guess what is causing that. I will test around.

**Comment by TheFloydman** [comment]
Huh, I'm used to seeing client crash logs end in "client", not "server". Anyway, you might also try making a new instance where the other mods are never added, or possibly delete the Mystcraft configs.

**Comment by Draskh** [comment]
Deleting Mytcraft's config let me join a new world.

The crash appears after forge stated that the backup level.dat is being used.

**Comment by Draskh** [comment]
I removed VanillaFix and FastWorkBench. The crash is always the same.
[crash-2019-01-23_18.33.40-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2788436/crash-2019-01-23_18.33.40-server.txt)

**Comment by Veovis-Muaddib** [comment]
Did your world crash or otherwise hard shutdown prior to this crash appearing?

I'm thinking one of your agedata_XX.dat files was left empty or in a corrupted state.

**Comment by Draskh** [comment]
No. It crashes in loading screen after "building terrain" has been appeared.

**Comment by Veovis-Muaddib** [comment]
I mean prior to this particular crash appearing.  The last time you successfully launched the game, did it shutdown safely?

**Comment by Draskh** [comment]
Yes, ever shut down safely.

**Comment by Veovis-Muaddib** [comment]
Inside your save file, back up and delete your agedata_XX.dat files and try launching again.

**Comment by Draskh** [comment]
I have already deleted all not needed .dat files. This hasn't had any effect. I had to add OpenBlocks back though. This was the only way to load the world.

Deleting all Mystcraft content also changed the crash. Seems that is not related to Mystcraft only.
[crash-2019-01-23_19.32.56-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/2788743/crash-2019-01-23_19.32.56-server.txt)

**Comment by Veovis-Muaddib** [comment]
Appears to be caused by a missing Villager profession with a Gravestone mod that creates graves for each profession.

https://github.com/NightKosh/Gravestone-mod-Extended/issues/197

**Comment by Draskh** [comment]
It creates a corpse for each profession no grave. The corpse can be found a resurrected.
The corpse should be vanished instead of being null if a profession is missing though.

**Comment by Veovis-Muaddib** [comment]
Good find, thanks for bringing it to our attention.  Remember that Mystcraft also adds a profession, though hopefully you won't uninstall it. :P

**Comment by Draskh** [comment]
I only removed it to identify the bug, which turned out not being Mystcraft's fault. So it is still in.
