### ISSUE TITLE
deleting Dimensions/Ages MC1.7.10/1.12.2

### ISSUE THREAD

**Issue by Pokihead** [XCompWiz/Mystcraft-Issues#339]
Hey first of all i love this mod and I know the game version Iam using is no longer supportet but this question is for MC 1.12.2 too.
Like the Header says i want to delete Ages in Mystcraft.
I know that it can be done by destroying the book, deleting the dim_myst"X" folder and the agedata"X".dat
X is a number.
But if I create a new age/dim Mystcraft keeps raising the dim number. That means if I had 5 Dimensions which I deletet all, the next Dim still would get the Number dim_myst7.
My question is now, is it possible to start again with dim_myst1?

**Comment by Veovis-Muaddib** [comment]
You should be able to rename an agedata and dim_myst folder to whatever number you want. (within MAX_INT or so)

But the real question is why?  Why does it matter what id is used?  You have over *4 billion* available, it's not like you're going to run out.

**Comment by Pokihead** [comment]
So if I rename both the dim number ingame (like on maps) changes?
Yeah I know its some kind of peculiarity by my own. So I want to have my order/system. 
But thanks I will test your suggestion :)

**Comment by Veovis-Muaddib** [comment]
You'll need to create new books, the /myst-agebook command should be sufficient.

**Comment by TheFloydman** [comment]
Like Veovis said, you have more than enough IDs, but if you use the command on this page (http://wiki.mystcraft.xcompwiz.com/v0.13:Commands) to mark an age for deletion, the ID will be recycled.

**Comment by Pokihead** [comment]
Ok rename and creating new books seams to work.
The Command for deleting/recycling doesnt seam to work, dont get any response from the game and both folder and agedata are staying

**Comment by TheFloydman** [comment]
Are you in the age when you use the command?

**Comment by Pokihead** [comment]
No I was in the Overworld

**Comment by TheFloydman** [comment]
![shoq](https://user-images.githubusercontent.com/22880199/53116476-9ef90180-34fd-11e9-962f-32211909a3cc.png)

**Comment by Pokihead** [comment]
ok haha sorry I "overread" this ^^
I'll try that tomorrow

and thanks for the help :)

**Comment by HellFirePvP** [comment]
Most likely/probably resolved.
