### ISSUE TITLE
Client crash when loading an age

### ISSUE THREAD

**Issue by WoolenSocks** [XCompWiz/Mystcraft-Issues#34]
Heyo, I made myself a void age to live in but when I tried to enter it I crashed and I crash every time I try to get on the server. The server itself seems to be running fine, I don't have access to the server files though so can't provide a server log atm.

Log:
http://openeye.openmods.info/crashes/028206d0ed1ce4b041ecb7614bf9856f

We're using verson 1.1.4 of the Wanderlust Reloaded pack

**Comment by XCompWiz** [comment]
No further information means dead report.
On the other hand, the changes to how descriptive books work in the next release should actually prevent this kind of thing in the future, anyway.
