### ISSUE TITLE
Crash while "Mystcraft bakes a cake" during creation of a new world

### ISSUE THREAD

**Issue by DatrixTHLK** [XCompWiz/Mystcraft-Issues#349]
Hi,

I know a lot of crash issues have mentioned this mod, I have crashed with this mod. I load up a new world Mystcraft bakes it's cake and then immediately crashes me to the main menu. I have a feeling it's because forge updated to 2835 and I'm using it right now. If I go back to 2825, it works just fine and finishes it's processes, so all I can assume is something in 2835 broke this mod.

Minecraft 1.12.2
Mystcraft: 1.12.2-0.13.7.02
Forge: 14.23.5.2835
Crash Log: https://paste.dimdev.org/xijusezufo.mccrash

**Comment by brisingraerowing** [comment]
I'm getting something very similar, just without the reference to Mystcraft code. I'll try downgrading forge.

**Comment by brisingraerowing** [comment]
I've looked into this further, and this was a Forge bug. It's fixed in Forge 2836..

**Comment by HellFirePvP** [comment]
Thank you for the information!

**Comment by DatrixTHLK** [comment]
So...forge can make mistakes after all...I see. Thanks for the response, I appreciate it!
