### ISSUE TITLE
Crystal portals only transport players

### ISSUE THREAD

**Issue by v1993** [XCompWiz/Mystcraft-Issues#350]
This seems realted to #345 and probably #254.

When I push mob (tested on pig) into crystal portal, it disappears but doesn't appear in destination. Same happens to minecarts: if I'm riding one, I arrive just walking.

That's pretty annoying because I can't build railroad via portal.

**Comment by v1993** [comment]
If it matters, I'm using more mystcraft, pages and mystcraft info.

**Comment by v1993** [comment]
Just discovered an interesting thing: it totally works if done within one world with intra linkage book.

**Comment by XCompWiz** [comment]
This should be working now.
