### ISSUE TITLE
Exception ticking world crash

### ISSUE THREAD

**Issue by ghost** [XCompWiz/Mystcraft-Issues#360]
Minecraft: 1.12.2
Forge 14.23.5.2823
https://paste.dimdev.org/amanakigom.mccrash

updated crash:
https://paste.dimdev.org/ucufikunid.mccrash

**Comment by TheFloydman** [comment]
Did you try to make a world out of chests?

**Comment by TheFloydman** [comment]
Or have chests in any way been added as Pages? Like those used as inputs for terrain or structures?

**Comment by ghost** [comment]
i don't think so

**Comment by TheFloydman** [comment]
The log indicates that large amounts of chests are being placed all around each other, which is causing you to lag out. Chests are not a useable block in Mystcraft by default, but they can be if enabled. Are you using a public modpack?

**Comment by TheFloydman** [comment]
Also come context would be helpful. Crashes occur at different times for different reasons.

**Comment by ghost** [comment]
> The log indicates that large amounts of chests are being placed all around each other, which is causing you to lag out. Chests are not a useable block in Mystcraft by default, but they can be if enabled. Are you using a public modpack?

how do you enable that

**Comment by TheFloydman** [comment]
There are several possibilities; it would be easier if I knew what modpack you are using.

**Comment by ghost** [comment]
I'm NOT using a modpack

**Comment by TheFloydman** [comment]
Then some further context, please. Minecraft crash reports are often lacking, and the two you shared are no exception. Please explain, in detail, what you are doing and what is happening right up until the crash happens. And what was your game like before you added Mystcraft?

**Comment by ghost** [comment]
I think the crash was caused be WorldGen Lag I think?

I uploaded a part of the log before the game crashed
https://paste.dimdev.org/yoqarucofu.mccrash

**Comment by TheFloydman** [comment]
The cascading world gen lag does not seem to be a problem in this case. Please explain further what you are actually doing when this crash occurs.

**Comment by TheFloydman** [comment]
And if you can share your custom modpack in a zip or something, that would be helpful.

**Comment by ghost** [comment]
Again I'm not using a modpack but here's a zip of (almost) all the mods I used plus the configs
https://drive.google.com/uc?export=download&confirm=6wNp&id=17ewjjiOlJUSuTP7Ok_slrc17TU8G6706

**Comment by TheFloydman** [comment]
If you are using a collection of mods, even if put together by yourself, it is a modpack. It just isn't published anywhere. I will try this out later when I have the chance. But please, please tell us under what circumstances this error occurs. We will have a hell of a time duplicating it if we don't know what to do.

**Comment by ghost** [comment]
ok
