### ISSUE TITLE
Crash when entering new age, no crash report

### ISSUE THREAD

**Issue by Shahelion** [XCompWiz/Mystcraft-Issues#364]
I found a descriptive book in an abandoned study in the overworld. The last time I found one of these, it worked fine (although the world was absurdly unstable). This time, if I try to go to the age, it loads into the world for about a frame or two, then just...closes. No crash report, nothing. I even have the mod that's supposed to make crashes boot me back to the main menu instead of closing the game.

The only thing odd in the console is this line at the end: 
Process crashed with exitcode -1073740940.

Full log linked below. I simply loaded up the game, entered the world (Morphic), placed a bookstand, placed the Descriptive Book into it, and clicked the linking panel. Then it crashed.

https://gist.github.com/Zsashas/6ca1aa52fa758eee24ac106440d0bf8c

**Comment by XCompWiz** [comment]
I don't recall adding descriptive books to treasure... I know I wanted to, but I think that might be an add-on doing that.
Though "no crash, just close" makes me think memory error. Maybe increase the memory your game is allowed to use? Also for the class path space.

I recommend asking for support on the Mystcraft Discord: https://discord.gg/pRGH45W
I'm currently closing support questions here; trying to limit this to bug reports. :)
