### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by damienlogos** [XCompWiz/Mystcraft-Issues#365]
Evening fine gents and lady gents,

I was testing out a variety of mods as my friends and I are loading a server up in a few days and I'll be the admin.  Mystcraft is my favorite mod of all time, but after cobbling together a list of mods we normally use and adding Mystcraft, I'm getting an exception ticking world crash.  It is happening repeatedly, and seems to happen primarily when flying around in creative (like I said, I'm testing) and I've loaded a lot of chunks in land.  Here is the bug report and the list of mods I'm using.  When I remove Mystcraft, the problem seems to go away.  I noticed mention of Villagers in the bug report.  Could it be a conflict with another mod using Villagers?

![image](https://user-images.githubusercontent.com/53421749/62026311-7c93a000-b18f-11e9-94fb-a5b41e412da3.png)

[crash-2019-07-28_22.08.36-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/3440546/crash-2019-07-28_22.08.36-server.txt)

**Comment by TheFloydman** [comment]
Extra Utilities 2 seems to be calling a method that doesn't exist, though it's unclear from the crash report if Mystcraft is missing that method or not. If there is a way to configure EU2 to stop accessing the Mystcraft villager, that might solve the issue.

**Comment by XCompWiz** [comment]
I'll close this as there was no follow up. Thanks for fielding it, Floydman. :)
