### ISSUE TITLE
Server crash on world time change: Exception ticking world

### ISSUE THREAD

**Issue by The-JC** [XCompWiz/Mystcraft-Issues#366]
I just updated my server the newest version (see log for versions). And every time I go to bed in one dimension the server crashes. It even crashes when I toggle downfall via command.
Also, the debug menu tells me that I'm on day 0, which is false. 
Also changing time works fine in dim 0.

Further, it seems like the whole world changed from an always daylight world to a night world with constant snow. I don't if this is relevant to the problem.

[crash-2019-08-03_00.34.49-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/3463071/crash-2019-08-03_00.34.49-server.txt)

**Comment by XCompWiz** [comment]
The agedata has been corrupted.
I recommend asking for support on the Mystcraft Discord: https://discord.gg/pRGH45W
Someone there may be able to help you recover that age's data. :)
