### ISSUE TITLE
Crash on load, unsure as to why

### ISSUE THREAD

**Issue by Esseit** [XCompWiz/Mystcraft-Issues#367]
Ive been trying to get this mod to load in, and found a version of it that is compatible with my version of forge but it catches a severe problem during mod loading that causes a crash. I've [attached](https://github.com/Esseit/crash-log/blob/master/crash%20log) the crash report which also lists the mods i have installed. If i could figure out what is the cause of the crash i can most likely handle it from there. Thank you in advance to anyone who is willing to help shine some light on this.

**Comment by Veovis-Muaddib** [comment]
I'm sorry to say, but that version does NOT work with your version of
forge.  The next release after that was a hotfix that did nothing but bump
the required forge version.

Is there a reason you can't move up just two minor releases from Forge 2768
to Forge 2770?  Is it that one or two mods require an older version of
Forge?

**Comment by Esseit** [comment]
i believe so yes, a few mods i have rely on this version of forge however i will try out using a different installation to see if it works.  Thank you for letting me know!

**Comment by Veovis-Muaddib** [comment]
If they're relying on *at least* that version of Forge, that's not
generally an issue.

If they specify *no higher than* that version of Forge, that's where you
might run into trouble.

I'd suggest going up to at least Forge 2770, and then updating Mystcraft
all the way.  There are some important bugfixes, especially the latest
release which fixes a bug between Mystcraft portals and Minecraft's updated
cheat detection.

**Comment by XCompWiz** [comment]
Looks like this support issue has been resolved. :) Thanks, Veo!
