### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by Shahelion** [XCompWiz/Mystcraft-Issues#368]
Happens since updating to the latest version.

https://gist.github.com/Zsashas/5837d01b8bafc4c1ea03a3d6b30f9402

**Comment by XCompWiz** [comment]
Gist is missing.
I recommend asking for support on the Mystcraft Discord: https://discord.gg/pRGH45W
Before reopening or making a new issue about this, please refer to [Bug Reporting Best Practices](https://github.com/XCompWiz/Mystcraft-Issues/wiki/Bug-Reporting-Best-Practices)
