### ISSUE TITLE
Crash when using link modifier - java.lang.NullPointerException

### ISSUE THREAD

**Issue by MrBurd** [XCompWiz/Mystcraft-Issues#37]
Pastebin:
http://pastebin.com/RLwGUtjN

Created a blank link book, linked it and placed in link modifier- upon mousing over any of the buttons in the link modifier, game crashes.

v0.11.0.20

**Comment by XCompWiz** [comment]
Thanks for the report and for catching this. :) I believe I've fixed it and it should work in the next dev build (which I'll probably push in a few mins).
