### ISSUE TITLE
Crash Upon World Startup

### ISSUE THREAD

**Issue by Watermelonbreak** [XCompWiz/Mystcraft-Issues#372]
https://paste.dimdev.org/uniluponoy.mccrash
forge-1.12.2-14.23.5.2838.jar
mystcraft-1.12.2-0.13.7.04.jar

**Comment by XCompWiz** [comment]
[Bug Reporting Best Practices](https://github.com/XCompWiz/Mystcraft-Issues/wiki/Bug-Reporting-Best-Practices)
