### ISSUE TITLE
Crash while loading dimension

### ISSUE THREAD

**Issue by ghost** [XCompWiz/Mystcraft-Issues#373]
https://paste.dimdev.org/uqapedacip.mccrash
[crash-2019-08-28_12.32.28-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/3552399/crash-2019-08-28_12.32.28-server.txt)
[crash-2019-08-28_12.47.01-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/3552400/crash-2019-08-28_12.47.01-server.txt)
[crash-2019-08-28_12.47.07-client.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/3552401/crash-2019-08-28_12.47.07-client.txt)
[crash-2019-08-28_12.30.37-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/3552402/crash-2019-08-28_12.30.37-server.txt)

**Comment by XCompWiz** [comment]
[Bug Reporting Best Practices](https://github.com/XCompWiz/Mystcraft-Issues/wiki/Bug-Reporting-Best-Practices)
