### ISSUE TITLE
Crash on start up while chunk loading

### ISSUE THREAD

**Issue by Spacedestructor** [XCompWiz/Mystcraft-Issues#377]
When i start up the server close before its done booting up it floods the log with a lot of
"Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Server thread/WARN [FML]: Mystcraft loaded a new chunk [161, 1] in dimension -2147483648 (Mystcraft) while populating chunk [160, 1], causing cascading worldgen lag."

it enteres the log for every chunk that is getting loaded on server start up and then it crashes with

"Server thread/WARN [FML]: Mystcraft loaded a new chunk [161, 1] in dimension -2147483648 (Mystcraft) while populating chunk [160, 1], causing cascading worldgen lag.
Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Server Watchdog/FATAL [minecraft/ServerHangWatchdog]: A single server tick took 60.00 seconds (should be max 0.05)
Server Watchdog/FATAL [minecraft/ServerHangWatchdog]: Considering it to be crashed, server will forcibly shutdown.
Server Watchdog/ERROR [minecraft/ServerHangWatchdog]: This crash report has been saved to: /./crash-reports/crash-2019-10-23_14.38.04-server.txt"

to this message is the full crash log attached.

[crash-2019-10-23_14.38.04-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/3762962/crash-2019-10-23_14.38.04-server.txt)

**Comment by XCompWiz** [comment]
Thanks for making a report.

This is in part because Vanilla isn't super happy about how Mystcraft's baseline dimension profiler works.
This should be resolved in the future. It should be harmless in the mean time. :)
