### ISSUE TITLE
Incompatibility with Railcraft?

### ISSUE THREAD

**Issue by xJon** [XCompWiz/Mystcraft-Issues#378]
Hi,
This crash was sent to me by a user playing my modpack, with both mods.
Happened shortly after creating a new world: https://pastebin.com/R7uw6nrN
Thank you.

**Comment by Veovis-Muaddib** [comment]
If this crash happens reliably, can you try disabling the Mineshafts symbol in the Mystcraft symbol config file?

**Comment by xJon** [comment]
I'm sorry but it happened once to a player, it does not happen every single time a new world is created, so I cannot reproduce it like that.

**Comment by XCompWiz** [comment]
I've written up a wiki page on bug reports: [Bug Reporting Best Practices](https://github.com/XCompWiz/Mystcraft-Issues/wiki/Bug-Reporting-Best-Practices)

If you can't reproduce it, I sure can't. :P
