### ISSUE TITLE
Incompatibility with SpongeForge

### ISSUE THREAD

**Issue by xJon** [XCompWiz/Mystcraft-Issues#379]
Hi,
Trying to run both the mod & SpongeForge results in a crash: https://pastebin.com/Zs3TBaGa
This was reported to Sponge here: https://forums.spongepowered.org/t/server-crashes-with-sponge-on-world-load/34243/2

**Comment by TimTinkers** [comment]
@xJon I managed to get SpongeForge and Mystcraft to run together by downgrading my SpongeForge to version 7.1.7-RC3775. I have no idea if this is the highest version that still works or not. I'm on Forge 2487.

**Comment by no-identd** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2704#issuecomment-498812177

**Comment by XCompWiz** [comment]
I'd be happy to help the SpongeForge team, but Mystcraft is built against Forge and doesn't explicitly support other mod loaders and platforms.

**Comment by no-identd** [comment]
Understandable. I hope you took a look at the issue over in the SpongeForge tracker, tho, if only because I suspect you might find the technical details of interest—independent of any intention of offering/adding support.

**Comment by XCompWiz** [comment]
I did, but didn't see any specific information that I could use nor contribute. Though I'll take this as a prod to actually  offer my assistance on that issue.
Thanks again. :)
