### ISSUE TITLE
Gui is passing null to the font renderer

### ISSUE THREAD

**Issue by frogfigther** [XCompWiz/Mystcraft-Issues#38]
The gui of the notebook, is passing a null string to the FontRenderer.

com.xcompwiz.mystcraft.client.gui.GuiInventoryNotebook.func_146976_a(GuiInventoryNotebook.java:125)

**Comment by XCompWiz** [comment]
While that's likely the most important line from the log, you should always post the full error, at least, if not the entire log.
I'll check it out. Please do post the rest of the error.

**Comment by frogfigther** [comment]
http://pastebin.com/53dBwksk

the null string crashes the vanilla font renderer aswell.

**Comment by XCompWiz** [comment]
Sorry for the delay.

One of the first things I note is the DragonAPI.  Reika's not checking for null somewhere that vanilla obviously allows to be null.  I'd take this to him, as, if you are going to replace the font renderer, you need to work like the vanilla one does.

Other than that, this gui doesn't exist anymore, and all my GUIs have been refactored, so I can't determine what exactly caused this issue.  The font renderer is no longer used from (what is now) GuiInventoryFolder directly.

Thanks for the report. Hopefully the next release won't have this issue. :)
