### ISSUE TITLE
Wonky Floating Island Villages

### ISSUE THREAD

**Issue by Oddlybird** [XCompWiz/Mystcraft-Issues#380]
I think the worldgen has interpreted this floating island as a very steep slope, rather than a discontinuous land segment -- so, it's placed buildings at various heights on the "slope".  I'm not sure if there's a way to fix that, but figured it was worth mentioning as an FYI.

[Here's an image dump.](https://imgur.com/a/9BbebOb)

**Comment by TheFloydman** [comment]
This has more to do with vanilla village spawn. To fix it Mystcraft would need a custom village spawn. Still a possibility, but I don't think that's likely.

**Comment by XCompWiz** [comment]
Floydman is correct. Mystcraft would have to have custom villages to resolve this issue. It's a "bug" in Vanilla.
Thanks for reporting it, though. :)
