### ISSUE TITLE
Intra-Linking Books don't close their UIs

### ISSUE THREAD

**Issue by SpectralMask** [XCompWiz/Mystcraft-Issues#381]
Using an intra-linking book in a bookstand or lectern keeps the GUI loaded after you link and allows you to take item from the slot, which removes it from the bookstand/lectern if the origin chunk is loaded, or creates a copy if the origin chunk is unloaded.

**Comment by XCompWiz** [comment]
Good catch!
I'm making a quick bug fix build and will have this resolved in it. :)
Thanks for reporting it!
