### ISSUE TITLE
Error message when putting symbol portfolio in workbench 

### ISSUE THREAD

**Issue by JSmids** [XCompWiz/Mystcraft-Issues#382]
https://paste.dimdev.org/solubikeya.mccrash. in Modpack "the 1.12.1 pack" putting portfolio pops a error. It still goes in the bench and stays in it though.

**Comment by XCompWiz** [comment]
Paste has expired.
I'd recommend bringing this up in the Mystcraft Discord: https://discord.gg/pRGH45W
Before reopening or making a new issue about it, please refer to [Bug Reporting Best Practices](https://github.com/XCompWiz/Mystcraft-Issues/wiki/Bug-Reporting-Best-Practices)
