### ISSUE TITLE
Permission nodes

### ISSUE THREAD

**Issue by aidan99davis** [XCompWiz/Mystcraft-Issues#383]
I am on 1.12.2 myst v-0.13.7.04 and I am attempting to prevent players with a specific rank from using mystcraft, but this has proven impossible as it doesnt implement permission nodes for things like interacting with books, using the blocks to craft descriptive ages etc.

Is this possible to add as it would make server administration much easier.

Thanks either way, great mod.

**Comment by XCompWiz** [comment]
I recommend asking for support on the Mystcraft Discord: https://discord.gg/pRGH45W
Suggestions tend to start there. You can also add them to the Trello suggestions board.
This repo is mainly for bug reports. :)
