### ISSUE TITLE
Can't load minecraft world when mystcraft is installed

### ISSUE THREAD

**Issue by CrypticGhost** [XCompWiz/Mystcraft-Issues#384]
I am using forge version 2768 and using minecraft 1.12.2 in Multi MC.  I can go into my world without mystcraft just fine but when it is installed I can't get past the building terrain loading screen. The game does not exit on its own but it just freezes. The first text doc is the log before clicking on a world. The second one is when a world is loading.
[log.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/4370838/log.txt)
[mc mstcraft.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/4370841/mc.mstcraft.txt)

**Comment by XCompWiz** [comment]
Looking at the log, I'd guess you added a mod that adds dimensions after visiting some Mystcraft worlds. You'll need to tell that mod to use a new dimension id or move or delete the Mystcraft ages.

I recommend asking for support on the Mystcraft Discord: https://discord.gg/pRGH45W
I'm going to be directing all support questions there, and trying to limit things here to bug reports. :)
