### ISSUE TITLE
Dedicated Server crashing when player enters a Descriptive Book

### ISSUE THREAD

**Issue by Syphini** [XCompWiz/Mystcraft-Issues#385]
Couple Pastes of server crash reports:
https://pastebin.com/CHHXFU50
https://pastebin.com/9tGqAfig

The main issue is in the title. I create a descriptive book, attempt to enter it, the server crashes
Player data needs to be modified or reset to let the player back into the server without it crashing again

I have used creative mode to create random and planned books all to the same result

I have attempted to play on singleplayer with and without the terrain generator mod that I'm also using. All singleplayer worlds worked fine without any issue when using descriptive books.

I haven't tried completely removing mods yet, but I'd rather not have to unless it's necessary

If anyone could give advice/help fix I would appreciate it.
Thanks for your time.

**Comment by XCompWiz** [comment]
Appears to be caused by OTGCorePlugin. :)
