### ISSUE TITLE
Libraries are created only at sea level 

### ISSUE THREAD

**Issue by mezoty** [XCompWiz/Mystcraft-Issues#40]
I have created a new world in latest build 10-0.11.1.00 and all out of discovered libraries in this world are created on sea level. That means many of them are underground libraries.

![2015-03-22_00 13 34](https://cloud.githubusercontent.com/assets/6764362/6768013/933622b0-d052-11e4-8c6b-c47f34473283.png)

![2015-03-22_00 20 19](https://cloud.githubusercontent.com/assets/6764362/6768016/adbd85ec-d052-11e4-96af-09951b1536ec.png)

![2015-03-22_00 36 54](https://cloud.githubusercontent.com/assets/6764362/6768017/c4b9a6ea-d052-11e4-847b-87288cb22886.png)

**Comment by XCompWiz** [comment]
ha.  Ooops. This was probably produced by me trying to fix the "split-level" libraries. :P

**Comment by XCompWiz** [comment]
Fixed for next release.
