### ISSUE TITLE
Access to 1.7.10 source code for continuation

### ISSUE THREAD

**Issue by Pilzinsel64** [XCompWiz/Mystcraft-Issues#407]
Hello @XCompWiz!

I would like to ask you for access and rights to the source code of Mystcraft 0.12.3.04 for 1.7.10 to be able to update build script, fix a few bugs and make minor improvements without changing the functionality. I want to use the updates mainly in my private modpack.

The last update is long time ago and you probably lost interest on 1.7.10 modding. But I still want to ask you - if you are willing to give ne access - if I should keep the code and the the resulting jar files private or if I am allowed to include the code or at least the jar in a public modpack (for the case I ever want to share my modpack publicy).

Please let me know if you agree and will to gain me access to the source code or not. Thank you!

Have a nice day! :)

**Comment by XCompWiz** [comment]
Chances are, no. Please contact me via the Mystcraft Discord, though. https://discord.gg/pRGH45W
