### ISSUE TITLE
Ink Mixer/Book Binder (aesthetic)

### ISSUE THREAD

**Issue by mcgraj3** [XCompWiz/Mystcraft-Issues#45]
For the life of me, I can't seem to get the Ink Mixer or Book Binder to rotate (through manual placement, Yeta Wrench has no effect). They seem to be hard-set to the direction of the compass. This doesn't affect their use so I consider this a minor issue.

**Comment by XCompWiz** [comment]
They don't have any rotation code to them. :P

**Comment by mcgraj3** [comment]
Oh, well, that would explain it I guess. :laughing:  Would be nice to see in a future release. Thanks!

**Comment by XCompWiz** [comment]
Fixed! :D
![Image](http://puu.sh/hegM5/6fa9d6a63d.png)
