### ISSUE TITLE
Adding a Folder to an ItemPortfolio

### ISSUE THREAD

**Issue by 55chevypickup** [XCompWiz/Mystcraft-Issues#48]
I was moving pages in to a ItemPortfolio and accidentally moved a folder and got the following crash.
It seems to of happened when there is an unknown page after upgrading from 11.0

http://pastebin.com/5tPy46JT

**Comment by XCompWiz** [comment]
It's actually because the folder had an empty slot, and the "addPage" logic was still called to add the null itemstack to it.  Ooops.
Fixed for next release.
