### ISSUE TITLE
Problem with Blockdestruction

### ISSUE THREAD

**Issue by Reyls** [XCompWiz/Mystcraft-Issues#49]
mystcraft-1.7.10-0.11.1.00
forge 1291
https://www.youtube.com/watch?v=SKBMXQK96f8

**Comment by Lunatrius** [comment]
#41, it will go away after roughly 15 minutes, when Mystcraft is done with the profiling.

**Comment by Reyls** [comment]
Do you mean 15 minutes after open or create the world?
