### ISSUE TITLE
Crash with latest version

### ISSUE THREAD

**Issue by xJon** [XCompWiz/Mystcraft-Issues#52]
http://pastebin.com/SJcSiikr
Just a random crash, I didn't do anything specific.
I'm not too sure who to blame; Mystcraft or Fastcraft.
Thanks :)

**Comment by XCompWiz** [comment]
I don't know either. I can look into it to see if I can puzzle it out.

**Comment by mSt3in** [comment]
Are entities spawning at an unfortunate time?  (right in the middle of chunk gen?)

**Comment by XCompWiz** [comment]
Looks more like something has completely removed the spawn list.  Not sure what could do that, but it wasn't Mystcraft.
Mobs are spawned during chunk generation (the population step, specifically), so nothing odd there.

**Comment by mSt3in** [comment]
with hats?

**Comment by XCompWiz** [comment]
I'm removing the bug tag since this isn't actually a bug in Mystcraft.
I'd like to help, but at this point I'd recommend taking this over to the Mystcraft forums. It's not likely to be a Mystcraft issue, but I'm happy to help and try and figure it out.
