### ISSUE TITLE
Re-profile a server

### ISSUE THREAD

**Issue by mSt3in** [XCompWiz/Mystcraft-Issues#55]
Hello,

It would be nice if there was a way to force the profiler to rerun.  This would be done after making considerable changes to ore spawn rates of other mods in an existing server.

...or am I mistaken and is this unnecessary?

Thanks again.

**Comment by XCompWiz** [comment]
You can just delete the myst_baseline.dat file. :) It's in the data folder, where agedata_XX.dat files are saved.

**Comment by mSt3in** [comment]
Thank you.
