### ISSUE TITLE
Crash during world profiling

### ISSUE THREAD

**Issue by Arrabal-** [XCompWiz/Mystcraft-Issues#57]
Getting a crash to desktop during world profiling on an existing world using the latest MystCraft release (0.11.2.01).

Crash report:  http://pastebin.com/QKgRfZ7q

From the crash report it looks like it is due to interactions between Mystcraft, and Custom Ore Generation.  Crash report indicates that MystCraft, FastCraft, ATG, and Custom Ore Generation all could be involved.  Had all of these mods working together with the following versions:

MystCraft 0.11.0.00
FastCraft 1.19
ATG 0.11.0
Custom Ore Generation 1.2.18

Tried updated version of the above mods and also removed them one at a time (and tried different combinations of mods).  Validated that MystCraft 0.11.2.01 works with:

FastCraft 1.19 & 1.21
ATG 0.11.0 & 0.12.0

MystCraft 0.11.2.01 and Custom Ore Generation 1.2.18 result in crash.  Removing Custom Ore Generation resolves crash issue.  Not sure if this is on the MystCraft side or the Custom Ore Generation Side so I am reporting to both.

**Comment by XCompWiz** [comment]
Thanks for reporting to both! :)

It's possible that the baseline world isn't providing something that COG expects to be there.  If you gent information as to what, that would be super helpful.
Can you link the report to COG here, please?

Also, an actual log file might be useful, rather than just the crash report. :)

**Comment by Arrabal-** [comment]
Per your request, here is a link to the COG issue report (and a new issue report to PFAA):  

https://github.com/lawremi/CustomOreGen/issues/64
https://github.com/lawremi/PerFabricaAdAstra/issues/45

Also, I did some further testing and reproduced the crash with minimal mods installed.  The installed mods are:

FastCraft 1.21
MystCraft 0.11.2.01
ATG 0.12.0
COG 1.2.18
Per Fabrica Ad Astra (PFAA) 0.2.23

PFAA adds a heavily customized ore generation configuration to COG and adds new ores, along with replacing all the vanilla stone and ore.  The crash only occurs when both COG and PFAA are installed with MystCraft 0.11.2.01.

Here are the log files, as requested (had to split into two pastebins to get around the size limit.  Part 1 goes through preInit):

Part 1:  http://pastebin.com/pwezyGZb
Part 2:  http://pastebin.com/dzskLKT9

**Comment by XCompWiz** [comment]
Fixed for next release.
