### ISSUE TITLE
server crash on start up

### ISSUE THREAD

**Issue by dezil** [XCompWiz/Mystcraft-Issues#58]
have got to the point of only having mystcraft-1.7.10-0.11.1.00.jar installed 

http://pastebin.com/ytJZ098P

**Comment by XCompWiz** [comment]
I'd like an actual log, not the crash report.

Also, I think I've seen this before.  Cauldron?

**Comment by dezil** [comment]
yea all fixed run the gen with forge then works fine with cauldron after that 

thanks for the quick reply though
