### ISSUE TITLE
Server crashes on startup with Mystcraft added to pre-existing pack

### ISSUE THREAD

**Issue by Soundtoxin** [XCompWiz/Mystcraft-Issues#64]
Crashlog: http://sprunge.us/eOBE
Server Modlist: http://sprunge.us/iVXG
Forge version: Forge 1343
Additional Info: This server is running Cauldron. I use a single plugin; Prism.

I've tried twice now to add Mystcraft to my pack, I waited a week in between. I had the same problem both times. I didn't really think the easter version would've fixed many bugs, but I gave it a show anyway. This is an existing map. We noticed jungles and swamps aren't generating at all with RWG and Biomes O' Plenty added, so we were hoping that adding Mystcraft could be our little work-around for this.

If you need any more info to figure this out, just let me know.

**Comment by XCompWiz** [comment]
See #62 
Here is a field missing on Cauldron that is necessary in Forge. I don't know why it isn't there, but it's a Cauldron issue, not Mystcraft.

You could try 0.11, as that version didn't have the initial profiling world, which is what needs the field.
