### ISSUE TITLE
Issue with reading Dimensions Names

### ISSUE THREAD

**Issue by Dyonovan** [XCompWiz/Mystcraft-Issues#65]
Hi, I am the author of TC Node Tracker and am having a compatibility issue between my mod and mystcraft.

CrashLog: http://pastebin.com/pzbnrdVg
TCNodeTracker Issue Line: https://github.com/Dyonovan/TCNodeTracker/blob/master/src/main/java/com/dyonovan/tcnodetracker/gui/GuiMain.java#L51

Only seems to be happening with latest version as far as I know. The issue seems to be when I call 

for (int i : DimensionManager.getStaticDimensionIDs())
            TCNodeTracker.dims.add(new DimList(i , DimensionManager.createProviderFor(i).getDimensionName()));

This is what seems to be causing the issue. The mod is completely client side and I know of no other way to get a list of Dim Names.

Any help would be great :)

**Comment by XCompWiz** [comment]
Mystcraft needs the agedata for an age to be able to tell you anything about that age.  Mystcraft providers don't work without a host world to provide them with data, and the age data must be sent to the client before the name will even be correct.
I would expect creating random providers of dimensions client-side to be problematic.

Furthermore, Mystcraft world names can change, so storing them like this would allow them to go stale.
When do you need these names?  Can you wait until there is actually an instance of the world to get it?
I rather feel I've seen client-mods get the names of all available dimensions before, though...  Looking through the code of existing map mods might provide insight.

**Comment by Dyonovan** [comment]
The list of Dim Names is recreated each time the GUI is opened so I am not worried about them going stale. All I actually store in the JSON is the Dim ID.

When I first started this project I tried to look for an open source map mod for examples but was unable to find one. Let me take a look again.

**Comment by Dyonovan** [comment]
Ok. after looking around, the only difference is they add a Try/Catch block. Hopefully just doing that will stop it from crashing.

Thanks for the help. I'll close the issue now.
