### ISSUE TITLE
Improve localization

### ISSUE THREAD

**Issue by Adaptivity** [XCompWiz/Mystcraft-Issues#7]
As stated here(last post by Adapt): http://binarymage.com/forum/viewtopic.php?f=25&t=1372&sid=2876a549d7e13b3a3c20a9e88f88801e&start=10

**Comment by XCompWiz** [comment]
http://i.imgur.com/Kp8LODE.png - Check. Localization done by the client that spawns the item (name persists).
As for translating biomes...  That's not something I can do readily. The biome names aren't localized in Vanilla, and I shouldn't do that localization myself. Maybe take it up with Forge?  I can (and will) provide a formatted localization key to allow the changing of the "Biome" segment at the end.
The block localization is of course still handled as normal, but I've added a similar "wrapper" key for the "Block" suffix.
Making the suffixes do nothing can be done by making them '=%s'.

Note that the "Block" and "Biome" suffixes were not necessary in English either, but added to help users differentiate between symbols and to facilitate search.  Additionally, Mystcraft strips "Block" and "Biome" from the end of text before running it through the wrapper, but this only works for English.

All done for the next release.
