### ISSUE TITLE
Volume Decreased In Mystcraft Dimensions?

### ISSUE THREAD

**Issue by Zoryn4163** [XCompWiz/Mystcraft-Issues#72]
I don't have any *true* proof that Mystcraft is the cause of this, but every dimension I create from Mystcraft has it's volume lowered by about 75% compared to the Overworld, Nether, and End.
I've tested this in 2 Mystcraft Dimensions, one a Void world with literally nothing in it, and another as a Mining world that's just using Standard terrain.
I'm using mystcraft-1.7.10-0.11.0.00.jar from the Direwolf20 1.2.1 FTB Pack. No crash logs/dumps/anything.

Edit: This does not occur in the Deep Dark dimension from ExtraUtilities, so it doesn't appear to be mod-dimensions in general. It also appears that the first block has the normal volume while the following 7 have diminishing volumes until it caps on the 8th placed/destroyed block, and all after are simply quiet until the dimension is reloaded.

**Comment by XCompWiz** [comment]
Weird. Does it make any difference based on location? So if you replace the first block and break it again, does it reduce the volume?
Can you provide a mod list?
Can you try testing this with just Mystcraft installed?

**Comment by Zoryn4163** [comment]
After placing the very first block the volume was lowered roughly 10-20%, and seems to have been multiplicative up to roughly 75%. I've had the server and clients update to use the latest Mystcraft (was trying to avoid doing so as the new symbol system removes a large amount of generating blocks such as Liquid Enderium and various molten materials, and personally prefer how the notebooks created worlds) and the issue has disappeared. It still saddens me that it was forced. I can try it with just  Mystcraft and the list of mods can be found at http://ftbwiki.org/Direwolf20_1.7_Pack - I suppose that since it's been fixed in the latest version there would obviously be no reason to search further, but wanted to post.

**Comment by XCompWiz** [comment]
The fluids being removed is other mod's doing, not Mystcraft's.  I need to allow that as other mods should have more say about their stuff than Mystcraft should.
The new folder system hasn't lost any functionality of the old notebook system. The folders function almost identically to the old notebooks, while portfolios are more useful for long term storage.
Glad the issue disappeared. I still have no idea why it would have appeared in the first place and I don't actually think it was Mystcraft doing it.

**Comment by Zoryn4163** [comment]
Well after updating Mystcraft it stopped happening, so that leads me to believe it was. Regardless we are now using the updated version. Would you happen to know what mod removes 90% of the Blocks pages?

**Comment by XCompWiz** [comment]
I don't know, but the log show tell us.  If you want to bring it up in a new issue or on the Mystcraft forums you can post a log of the game startup as a pastebin. Then I can help. :)
