### ISSUE TITLE
Worldgen crashing with Cauldron (Forge 1388) On TPPI2 Modpack

### ISSUE THREAD

**Issue by Sayshal** [XCompWiz/Mystcraft-Issues#73]
So on the TPPI2 Modpack v0.1.4 (SuperWhaleKick on FTB Launcher), I've managed to get it all working with cauldron except for Mystcraft version 0.11.5. I've tested it and it works correctly on 0.11.0. 

The error is that it was creating a world called DIM_Myst-2147483648

Any help? I know Cauldron is unsupported but it's something between 0.11.0 and 0.11.5

**Comment by XCompWiz** [comment]
Mystcraft creates that dim on purpose.  This is not an error.

**Comment by Sayshal** [comment]
Alright well it's still what I'm seeing in my crash reports:
0.11.5: http://pastebin.com/e98znBhQ

**Comment by XCompWiz** [comment]
Please see issue #66 :)
