### ISSUE TITLE
Modifiers, Blocks missing *tons* of pages compared to release 11.0.00

### ISSUE THREAD

**Issue by Zoryn4163** [XCompWiz/Mystcraft-Issues#74]
Title. According to my other post other mods were suggested as the cause, but as far as I'm aware no other mod is denying Mystcraft pages from being created, and even the symbols.cfg is missing them. For reference, pages like "Molten <METAL>", "Liquid Enderium", and "Destabalized Redstone" are missing.

See the following for all the logs/configs/modlist: https://drive.google.com/open?id=0B-_iReN21PiINGVTaG1QTzNsSkU&authuser=0

It has: fml-server-latest, latest, ModList, [Config/core, Config/instabilities, Config/symbols (and a sub-folder for the older 11.0.00 configs)], and I can provide whatever else you'd like. (The biggest reason I'm using drive is because the fml-server-latest file is too big for pastebin [and I don't want 10 different links], but if you *really* want them as pastebins I will and the fml-server-latest will be split to *many* different pastebins)

**Comment by XCompWiz** [comment]
Excerpts: http://pastebin.com/rCqLM6Lc
Those fluids listed there have been disabled by Tinker's Construct.  Most "Molten *" fluids are disabled.

There's also some empty log messages right after that, which I'll need to look into.

I think the only things that get log messages are the IMC actions.  Anything disabled though the API is probably not logged.  I'll change that.

As a note, most mods probably haven't updated to Mystcraft's new API system yet, so anything that was using the old API to blacklist symbols probably isn't doing so now... Try a newer version of Mystcraft. ;)

**Comment by Zoryn4163** [comment]
Okay that makes much more sense.
I found the TC code that does it: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/plugins/imc/TinkerMystcraft.java (Line 45 as of writing, at least to my knowledge)

Is there any way you could possibly add a config to Mystcraft to disable FMLInterModComms.sendMessage("Mystcraft", "blacklistfluid", <fluidName>) calls?
TC has a post about it where they have refused to add a config option to disable this feature as they see it as 'game breaking', but I'd rather not use unofficial versions of it or self-compiled variants.
I don't quite understand why IC2 UU-Matter was removed as well though, as I don't believe IC2 has anything to disable it. At what version was the 'blacklistfluid' call added?

**Comment by XCompWiz** [comment]
IC2 *might* have been using the API itself, so that's a possibility.  If it reappears with a newer version of Mystcraft you'll have your answer.

And I refuse to take the blacklist option away from mods.  I added the IMC message handler specifically for cases where it was deemed "game breaking" within a mod to have a symbol for a fluid.
Ultimately, I feel players should be able to play as they wish, but I'm also not willing to break other mods for you.

**Comment by Zoryn4163** [comment]
Very well. I have the mindset that the end-user should be able to deem whether X is game-breaking or not, and if they wish to play with it then they should be allowed to. Thank you for the insight on what was causing it.

**Comment by XCompWiz** [comment]
I agree, but I can't take the choice from other modders here.
