### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xee1** [XCompWiz/Mystcraft-Issues#79]
Hi @XCompWiz , I get this errors in console:
https://gist.github.com/Xee1/fbef8e94245e8cbec4d2
forge-1.7.10-10.13.3.1400
mystcraft-1.7.10-0.11.7.00
MineFactoryReloaded-[1.7.10]2.8.0-104

**Comment by XCompWiz** [comment]
Thanks for the report!  I've fixed this for the next release, I believe.

**Comment by Xee1** [comment]
Thanks! Keep it up!
