### ISSUE TITLE
Server crash but client ok

### ISSUE THREAD

**Issue by ChaosXten** [XCompWiz/Mystcraft-Issues#80]
I mentioned this on another issue related, but didn't realize it was closed, sorry - https://github.com/XCompWiz/Mystcraft-Issues/issues/60

I had a stable version of Mystcraft on my server at version 0.11.0.00 - my last update to my custom modpack was back in March, so I set aside time to work through all the updates today.

As you can see in the information I posted in the closed thread, Mystcraft was crashing the server on world-gen. After that post I finally got it working by reverting back to version 0.11.0.00. I then thought I would run through each update, but as soon a I launched with 0.11.1.00 it did the same thing (gist links are below with the crash and fml log file from that launch)

Crash log - https://gist.github.com/ChaosXten/d98f23df285b4a3f28e8
fml latest log - https://gist.github.com/ChaosXten/9e40a7d7cf101e8376b1

Thanks ... PopsRocker

**Comment by XCompWiz** [comment]
See: #62
