### ISSUE TITLE
Server crash on update to 0.11.8

### ISSUE THREAD

**Issue by CurePindal** [XCompWiz/Mystcraft-Issues#81]
Hello!
Ive tested to update my server from 0.11 to 0.11.8 and Mystcraft crashed the server on startup! Sad Panda.
Unfortunatly my Java Mojo isnt good enough to understand the Mumbo Jumbo of the crash, so maybe somebody can lend a helping hand and explain what went wrong and how to fix it?

Thanks!

Crashlog: http://pastebin.com/T9zZVScj

**Comment by XCompWiz** [comment]
See: #62

**Comment by CurePindal** [comment]
So in short, you made it with a later forge than the recommended 1291? Why the heck?

**Comment by XCompWiz** [comment]
Nope. The version I'm building against is 1.7.10-10.13.0.1180. Cauldron is at fault here.

**Comment by CurePindal** [comment]
Ah, ok! Thanks for clarification! Cauldron land didnt become easy to tackle since Blood moved on..

**Comment by XCompWiz** [comment]
Ya, the DMCA caused some pretty massive waves.  Good luck!
