### ISSUE TITLE
crash on entering a mystcraft age

### ISSUE THREAD

**Issue by darkmdbeener** [XCompWiz/Mystcraft-Issues#82]
When someone enters a statecraft age, the server will crash. The server is ok to restart and ok when playing. The server then kicks out the player when they try to enter the age. 

attached are the crash reports if that is helpful. the mystcraft being used is the one in direwolf 1.3.1

http://pastebin.com/xRQqi6CS

http://pastebin.com/ZQqHFzuQ

**Comment by XCompWiz** [comment]
These crashes look to be caused by and within Quetzi's Morpheus.  Please report this to Q. :)

**Comment by darkmdbeener** [comment]
would disabling this fix the issue?

**Comment by Quetzi** [comment]
Looks to me like the player has traveled to a non existing age/dimension, the client stacktraces show what is causing Morpheus to crash https://github.com/Quetzi/Morpheus/issues/10#issuecomment-102218104

**Comment by XCompWiz** [comment]
Looks like the problem was resolved. Wish we knew what caused it, but if anything shows up again later let us know.
