### ISSUE TITLE
Crash with BiomeTweaker

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#83]
https://gist.github.com/keybounce/93298769ae5b048b1f69

**Comment by keybounce** [comment]
Still happening with 11.9.04.

**Comment by keybounce** [comment]
Gar.

It does not happen in a modpack with just TF and mystcraft.
Ages work just fine, even with the TF root systems, no crashes.

Attacking my mod list, trying to see what makes it break.

**Comment by keybounce** [comment]
Found!
Biome Tweaker is triggering it.
More specifically, here's some biome tweaks that are causing it.

https://gist.github.com/keybounce/c9eac2bc23075c1fac50

**Comment by keybounce** [comment]
It seems to be triggered by having weight 1 on chickens ...

**Comment by keybounce** [comment]
This one-line change in my config triggers it
keybounceMBP:BiomeTweaker michael$ git diff
diff --git a/SillyBiomeTops.txt b/SillyBiomeTops.txt
index 215f5e7..0f4fc04 100644
--- a/SillyBiomeTops.txt
+++ b/SillyBiomeTops.txt
@@ -20,5 +20,5 @@ restoreChickens = forBiomesOfTypes("Snowy")
 reducedChickens.removeSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE")
 reducedChickens.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 1, 2, 2)
 killChickens.removeSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE")
-restoreChickens.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 1, 2, 1)
+# restoreChickens.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 1, 2, 1)

**Comment by keybounce** [comment]
Confirmed. Minimum crash is Mystcraft, biome tweaker, and this tiny config:

```
# Snowy chickens? Sure, it's another option ... and it shows off the snow piles.

restoreChickens = forBiomesOfTypes("Snowy")
restoreChickens.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 1, 2, 1)
```

Biome tweaker reports a sample changed biome:

... Ohh, some of these biomes have nothing in the CREATURE list, and now have a single entry of weight 1 ... that sounds like a likely corner case.

Other than that, Whoops! Chickens are in the spawn list twice (in some biomes), once at (normal) min 4, max 4, weight 10, and (new) min 1, max 2, weight 1.

**Comment by XCompWiz** [comment]
Did you try this without Mystcraft?

**Comment by keybounce** [comment]
Yes, I tried it without mystcraft.

Hmm ... which biomes would run into this? Frozen ocean, but that won't generate in the overworld. Frozen river -- does that still generate in the overworld? (I thought it did). ... Ice plains! That does generate in the overworld, and triggers this (nothing spawns there normally, and I was not aware of that). I have been over frozen areas, but I'm not certain if I've been over an ice plains.

Hmm, interesting. Ice Plains Spikes won't trigger this -- Draco added his mountain goats there :-).

**Comment by XCompWiz** [comment]
What are those numbers to the side? Have you tried 1, 2, 2? or 1, 1, 1?

So, outside of Mystcraft making it easy to get the biomes which produce the issue, it's not a Mystcraft issue. The code crashing is vanilla, and the line is probably this one:
``` int i1 = spawnlistentry.minGroupCount + p_77191_6_.nextInt(1 + spawnlistentry.maxGroupCount - spawnlistentry.minGroupCount); ```
If that is ever 0 or lower then it will crash. That's not the list size, though, that's the entry structure's data. I somehow suspect a nice little sanity check for "assert minGroupCount <= maxGroupCount" would be handy here...

**Comment by keybounce** [comment]
The numbers are minimum, maximum, weight.
It seems to be triggered by a total weight of 1.
