### ISSUE TITLE
Not sure if Mystcraft, Looking glass or my puter

### ISSUE THREAD

**Issue by dylanwi** [XCompWiz/Mystcraft-Issues#87]
http://pastebin.com/bYjQ54Uf
Placing a descriptive book on a book stand, or just in the world (link books don't crash me) and opening the gui. Crashes me.

**Comment by XCompWiz** [comment]
Have you used this descriptive book, yet?

**Comment by XCompWiz** [comment]
Ah!  Looking through the lines it looks like it couldn't get a symbol for biome distribution logic. Have you disabled all of the biome distribution symbols?

**Comment by dylanwi** [comment]
I changed some configs that enabled biome distribution pages and I didn't crash and was able to not only open the gui (looking glass is really cool) but was able to transport. (Sorry it took a while to reply, I had to go to bed and I was at school all day)

**Comment by XCompWiz** [comment]
Glad that fixed it. I added something to the Mystcraft  startup checker so that it will warn people of such issues in the future. :)
