### ISSUE TITLE
Suggestion: WAILA Tooltip Improvement

### ISSUE THREAD

**Issue by shadowfacts** [XCompWiz/Mystcraft-Issues#89]
In the WAILA tooltip for the Lectern and Bookstand blocks the name of the book contained should be shown, this would make it much easier to quickly find a certain book if a player has a large number of them.

**Comment by heldplayer** [comment]
This is something up to either the developer of WAILA, or an addon maker.

A nice suggestion is to go to your Mystcraft config file and enable the names above lecterns and bookstands to show (not sure what option that is, though)

**Comment by shadowfacts** [comment]
See tterrag1098/WAILAPlugins#35
