### ISSUE TITLE
DIM_MYST-2147483648?

### ISSUE THREAD

**Issue by CurePindal** [XCompWiz/Mystcraft-Issues#90]
Each new game from 0.11.8 onwards created a DIM_MYST-2147483648 Dimension! That number is the max for a long int variable. 
Whats that and why? Is it a bug or something?

**Comment by keybounce** [comment]
It is used for the profiling age. It is normal mystcraft behavior.

**Comment by XCompWiz** [comment]
It's actually MIN_INT, not max (though it is MAX_INT +1).
Keybounce is correct, that's standard behavior and functioning correctly. It's the reason Mystcraft announces it is baking a cake.
Now if that dimension is being saved then we have an issue. Creating a folder seems to be a requirement, though, and it won't let me prevent that.
