### ISSUE TITLE
Fatal error on world load. No crash

### ISSUE THREAD

**Issue by taj1994** [XCompWiz/Mystcraft-Issues#92]
Whenever I try to load a single-player world using my custom modpack, I get a message saying "A fatal error has occurred, this connection is terminated" before ending up at the multiplayer server select screen. [Here is a screenshot](http://i.imgur.com/4PonoFB.png) (not from tonight, but the screen is exactly the same). This only happens when Mystcraft is installed, but I'm not sure if it's a conflict with another mod, since it doesn't actually crash... Logs are below:

- [latest.log](http://pastebin.com/N7gMdxBc)

- [fml-client-latest.log](http://paste.ubuntu.com/11490113/)

I'm using Minecraft 1.7.10, with Forge 10.13.3.1408, Mystcraft 0.11.11.00, and (just in case it matters) LookingGlass 0.1.0.00, with about 188 other mods. If a full list of mods is needed, I can get that as well (if you also need version numbers, it'll take me awhile to do that)

**Comment by heldplayer** [comment]
latest.log and fml-client-latest.log do not appear to be related to eachother.

The crash you're getting is related to my NEI addon, remove it for now. There will be a new version for the latest version of LookingGlass soon.

**Comment by taj1994** [comment]
>latest.log and fml-client-latest.log do not appear to be related to eachother.

I didn't know which log I needed, and they were both last modified at the same time, so I included both. Lol

>The crash you're getting is related to my NEI addon, remove it for now. There will be a new version for the latest version of LookingGlass soon.

That worked. Thanks! I'll keep an eye on your thread for any updates, since it really is a useful mod
