### ISSUE TITLE
[Sugestion] Toggle option in the config for disabling Baseline dimension profiling or rewrite it to cause less lag.

### ISSUE THREAD

**Issue by border999** [XCompWiz/Mystcraft-Issues#93]
Upon loading any new world I receive a very large lag spike and my minecraft freezes for a number of minutes.
During this time the only commands that work are those for altering gamemodes. My terrain generation also becomes incredibly slow with very long periods where my minecraft simply stops responding.
If you are unwilling to create this option then I ask that you look into some way of alleviating the lag amount of lag that it causes.
Perhaps a viable idea would be to have baselining be carried out while the world is being created and finish with it as well, this would most likely increase generation time but I think this is a small price to pay.

**Comment by XCompWiz** [comment]
I'm really tempted to close this outright.  You didn't even bother to spell check the title.

I assume that by "baselining" you mean the baseline dimension profiling.
I assume you want a config option to disable it.

I also assume that it causes you lots of lag during the initial world startup, and that you'd rather have unstable worlds than wait for it to finish.

You don't bother to discuss what you wanted or why.  You don't talk about the kinds of lag you are getting. You don't talk about any of the issues, or ask what can be done or why it works the way it does.

Outside of my irritation at this poorly created suggestion ticket, I don't want to create this option as I'd rather work out the issues in the system.  Providing an "easy way out" means it wouldn't get used and thus wouldn't improve.

There are some things I could try.  Let's exhaust them first, OK?

**Comment by border999** [comment]
Now this is the kind of feedback that I have been looking for. Though it would appear that being horrible at making a description brought your attention to it. 
You are correct in assuming that what I meant by "baselining" I meant baseline dimension profiling. As for the lag issue, my minecraft completely freezes for 5 minutes and until the baseline actually finishes I'm unable to use any form of command except switching gamemode. 
Terrain generation also is spotty at best, as well as long periods where my minecraft simply freezes and becomes unresponsive for extended amounts of time.
What I wish is that someone would find a way to have baselining be completed AS the world is finished generating. Why I want this is as simple as any gamers desire for less lag.
I ask if there is any work on those issues that can be done to alleviate them.
Also, seeing the logic you present on why you won't make it an option, I see that you are at least aware of the problem by are working at solving it in a different way. Respect to you.

**Comment by border999** [comment]
Are these alteration to your liking?

**Comment by XCompWiz** [comment]
This is pretty much the response and feedback I've always given. I'm sorry you had to annoy me to make me phrase it in a way that you understood.

The baseline profiling generates one chunk every tick until done, and does the profiling in another thread.  At this point the amount of lag generated doesn't affect my machine at all, so I'm having difficulty determining how to reduce it.
I may try generating chunks less often, but that means that we start trading on the time to completion.  Less lag, but for a longer time.

After the completion of the baseline profiling (when the "cake is baked") the lag from baseline profiling ends.  If you continue experiencing lag, it's something else.

It sounds like you have a mod or mods that make terrain generation take longer.  You might want to try with just Mystcraft installed and see if you still experience those issues.

**Comment by KlutzLament** [comment]
border999, what are the specs of your machine? Processor, graphics card, etc.

**Comment by border999** [comment]
Processor:  Intel(R) Celeron(R) CPU1017U @ 1.60GHz
Graphics: Intel(R) HD Graphics
Storage capacity: 131GB free of 284GB

**Comment by border999** [comment]
how much lag do you think Ars Magica produces on average for players?
