### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by xJon** [XCompWiz/Mystcraft-Issues#95]
The report: http://pastebin.com/FKKU6A5j
What does that? I see Hats, Fastcraft and Mystcraft. Who should take the fault?
Thanks for any answer.

**Comment by XCompWiz** [comment]
I don't like the idea of people "taking fault."  "Where is the error occurring?" is fair, but blaming someone for an issue is the wrong way to go about things.

From the looks of it, the Hats mod makes a call to vanilla that then crashes on a null pointer exception.
From what I can tell, it would suggest that the world object for the mob spawner in use was somehow null.  I'm not sure what mob spawner was in use, so I can't say how or why that could be. I'd say you'll need to ask iChun about this one. :) Looks like an issue in Hats.
At the very least, iChun will have a better idea of what is breaking.

**Comment by xJon** [comment]
:+1:
