### ISSUE TITLE
Weird crash #2

### ISSUE THREAD

**Issue by xJon** [XCompWiz/Mystcraft-Issues#96]
http://pastebin.com/fJwNB7Es

I just messed a bit with Mystcraft items, the game freezed and then crashed.
I can see in the crash report RecurrentComplex, which is a mod that generates structures.
I've posted an issue also on RecurrentComplex' repository if it's due to that mod.

What do you think?
Thanks!

**Comment by XCompWiz** [comment]
Don't come to my bug tracker with other mod's bugs when you know Mystcraft has nothing to do with it.  I can't help and it just wastes everyone's time.

**Comment by xJon** [comment]
@XCompWiz How could I possibly know it's not a Mystcraft bug? I didn't mean to waste your time, but understand my position. Thanks anyway.

**Comment by XCompWiz** [comment]
Sorry, it seemed from your description that you knew it to be a Recurrent Complex issue.

**Comment by xJon** [comment]
@XCompWiz It's okay, sometimes I can be hard to fully understand with my English skills :)

Basically the problem started when I updated a bunch of mods. I can see only Fastcraft, RecurrentComplex, and Mystcraft in the crash log. From those three, I updated only Mystcraft.
I tried contacting the author of RecurrentComplex, and he said he's not sure and it might be "chained chunk generation", that can be related to Fastcraft.

So in general I'm not sure what causes that, but I want to know your opinion.
Thanks :)

**Comment by XCompWiz** [comment]
Fastcraft does force some chunk gen. So does Mystcraft, but Mystcraft avoids chaining chunk gen at all. It's generally only other mod generation or vanilla generation that does that.  Mystcraft's large trees still cause problems there, so an age with them may cause several chunks to load at one population step...  I should fix them...

At any rate, try without any of the tree mods and see if you can reproduce the issue otherwise.

**Comment by xJon** [comment]
I will try if I'm able to reproduce the crash without Mystcraft, or without any of the other two mods, and report back tomorrow.

**Comment by xJon** [comment]
@XCompWiz What do you mean "any of the tree mods"? :)

**Comment by XCompWiz** [comment]
three*  Any of those three mods. Sorry for the typo.

**Comment by xJon** [comment]
Unfortunately I'm unable to understand the pattern, tried with and without and I don't understand really what causes that. Sometimes it happens, and sometimes it doesn't happen. Very weird..

**Comment by Bogdan-G** [comment]
@xJon certain generation objects in certain order
