### ISSUE TITLE
Cross-mod fluid blacklist blocks all fluids

### ISSUE THREAD

**Issue by CombatZAK** [XCompWiz/Mystcraft-Issues#97]
I believe I may have found a bug in the cross-mod fluid blacklist logic in Mystcraft. While running MystCraft with TConstruct, I noticed non-TConstruct symbols were being removed from the list of available symbols, despite the fact that TConstruct did not send IMC messages to blacklist those particular fluids.

Here is a snippet of all the symbols that TConstruct blacklists (basically all of its molten metal symbols):
```java
public void init (FMLInitializationEvent event) {
        final Fluid[] fluids = new Fluid[] {
                // precious tinker fluids
                moltenGoldFluid,
                moltenSteelFluid,
                moltenEmeraldFluid,
                moltenArditeFluid,
                moltenCobaltFluid,
                // all alloys
                pigIronFluid,
                moltenBronzeFluid,
                moltenAlumiteFluid,
                moltenAlubrassFluid,
                moltenManyullynFluid,
                // precious TE fluids
                moltenEnderFluid,
                moltenSilverFluid,
                moltenInvarFluid,
                moltenElectrumFluid,
                moltenShinyFluid,
                moltenSignalumFluid,
                moltenLumiumFluid,
                moltenMithrilFluid
        };

        TConstruct.logger.info("Mystcraft detected. Blacklisting Mystcraft fluid symbols.");
        for(Fluid fluid : fluids)
        {
            if(fluid == null)
                continue;
            FMLInterModComms.sendMessage("Mystcraft", "blacklistfluid", fluid.getName());
        }
}
```

The actual fluid names are not shown there but I have no reason to doubt that they are correct. These blacklists entries do not include, ThermalExpansion liquifacted coal or energized glowstone. Yet when using TConstruct alongside mystcraft, those particular symbols disappear. After TConstruct is removed, the symbols are once again visible.

I glanced at the decompiled source of Mystcraft 0.11.11.0, the latest version available on Curse, and I think I found the problem: a simple logic error in the **ModSymbolsFluids.modsLoaded** method. However, I will not post the source here without your permission.

Please let me know if you need more information.

**Comment by XCompWiz** [comment]
If you've spotted the error, pleas let me know. :) Thanks for the consideration of not posting the source! :)

**Comment by CombatZAK** [comment]
Here are the the first few lines of the **ModSymbolsFluids.modsLoaded** method, the part the checks if the fluid has been blacklisted

```java
public static void modsLoaded()
{
  Map<String, Fluid> map = FluidRegistry.getRegisteredFluids();
  for (Map.Entry<String, Fluid> entry : map.entrySet())
  {
    Fluid fluid = (Fluid)entry.getValue();
    if (blacklist.contains(fluid)) {
      return;
    }

      //...does the important stuff, makes the fluid symbol visible...
```

So, my understanding is that the modsLoaded method on this class iterates through all the fluids in the Forge FluidRegistry, checks to make sure they're on the blacklist, and if they're not, creates a symbol for them and makes it available in Mystcraft.

The trouble is the logic for checking whether a fluid is on the blacklist.

```java
if (blacklist.contains(fluid)) {
  return;
}
```

I believe this has the effect of dropping out of the entire method when the first blacklisted fluid is encountered. Further fluids are not even examined. When I looked at core.cfg with TConstruct loaded, the balance section had only two fluids listed, and there should have been many more (all the Thermal Foundation fluids, for example). Those two fluids probably just happened to be higher up in the registry than the first TConstruct fluid to be blacklisted. TConstruct is probably the only mod I'm using that's blacklisting fluids because removing that mod caused all the ThermalFoundation fluids to once again be visible.

I think the intended logic here is as follows:
```java
if (blacklist.contains(fluid)) {
  continue;
}
```

This would have the effect of skipping the current fluid if it's on the blacklist, and examining the next one. Of course this all assumes I understand the code correctly, and that isn't a sure thing.

**Comment by XCompWiz** [comment]
Errm... yes. Very simple error, but it is indeed the cause of the problem.  I've fixed it.  Good catch! :D
Thanks a bunch!

**Comment by CombatZAK** [comment]
I'm glad I could help. Mystcraft is an amazing mod, and you've done an incredible job with it.
